### ISSUE TITLE
Updating a test requires rebuilding everything

### ISSUE THREAD

**Issue by jaylorch** [verus-lang/verus#1050]
If I run Verus tests, then make a small change to a single test, then test again, it takes minutes. It looks like nearly all of Verus is getting rebuilt even though all that's changed is the test file.

For instance, if I run `vargo test -p rust_verify_test --test open_invariant`, then edit `rust_verify_test/tests/open_invariant.rs`, then run `vargo test -p rust_verify_test --test open_invariant` again, it takes several minutes to start the test, during which it displays informational messages suggesting it's compiling a huge variety of crates.

**Comment by utaal-b** [comment]
This should not be happening (`vargo` and `cargo`) should do the right thing and only rebuild what's changed and its dependencies.

I have seen this happen with an interaction with rust-analyzer if it's configured to use different feature flags, thus invalidating the cache. Are you using rust-analyzer? There's a `.vscode/settings.json.template` you can copy and edit to configure it correctly for Verus (if you're on vscode). If it's not there, we should add this info to CONTRIBUTING.md.

**Comment by jaylorch** [comment]
Hmm, I'm just doing all this from the command line, not from inside vscode.

**Comment by jaylorch** [comment]
@utaal-b figured out my issue: I had an instance of VS Code running in the background, and even though I wasn't actively using it, it had a `rust-analyzer` process running that was interfering. That process was noticing the changes I made and marking the crate as changed. He showed me how to fix the issue by using the proper VS Code settings. I'll add instructions about that to `CONTRIBUTING.md` to close this issue.
