### ISSUE TITLE
Verifying all files in crate with one command

### ISSUE THREAD

**Issue by enjhnsn2** [verus-lang/verus#1057]
Hello,
I've been looking at Verus to see if it would be suitable for a project, and while it verifies individual Rust files well, I cannot for the life of me figure out how to verify a whole crate at once. 

The command I've been attempting is: 
```Bash
vargo run -p rust_verify --release -- ../../myproject/kernel 
```
(from the `source` directory), however this results in 
```
error: couldn't read ../../myproject/kernel: Is a directory (os error 21)

error: aborting due to 1 previous error

```
so clearly I am not specifying this correctly.

I've read through the start of ther Verus book and INSTALL.md, but don't see anything about verifying whole projects.
Is it possible to verify a whole crate at once/is there documentation somewhere on how to do this?

Thanks

**Comment by parno** [comment]
I think you can just point Verus at your `src/main.rs` file for an executable project, or `src/main.rs` for a library project.  You'll need to add `--crate-type=lib` for the latter.  Sorry that the documentation isn't clearer!

**Comment by enjhnsn2** [comment]
Ah, that worked great. Thanks, I'll close the issue
