### ISSUE TITLE
Rust version of target code

### ISSUE THREAD

**Issue by panda2134** [verus-lang/verus#1068]
What's the rust version used for the target code that will be verified? My current project is using rust nightly, but verus seems to be incompatible with that. Is it possible to change the rust version used (like `rustup toolchain nightly`, but for verus)?

**Comment by jaybosamiya** [comment]
This is not officially supported, but if you swap out [this line](https://github.com/verus-lang/verus/blob/main/rust-toolchain.toml#L2) for 
```
channel = "nightly-2024-02-08" # (not officially supported)
```
then it _might_ work. That particular date is the date of 1.76.0 release, thus it is the most likely nightly version to work.

**Comment by utaal** [comment]
> That particular date is the date of 1.76.0 release, thus it is the most likely nightly version to work

I'd also try a nightly ~7 weeks before the date of the release, which is when the release branch is forked and stops getting the commits from `main` (except for specific backports). See https://forge.rust-lang.org for more information on when version branches are branched from master.

I'm going to close this, but feel free to re-open if you need more help.
