### ISSUE TITLE
How to conveniently verify submodules recursively?

### ISSUE THREAD

**Issue by marshtompsxd** [verus-lang/verus#1077]
Hi Verus team, I am trying to find an easy way to verify all the submodules recursively inside one module (like using a wildcard?). Concretely, I was looking for something like `--verify-module foo::bar::*`, and then Verus will verify module `foo::bar` and all the submodules inside `foo::bar` recursively. However, for now the only way to do it is to specify all the submodules one by one to Verus.

**Comment by jaybosamiya** [comment]
Relevant: https://github.com/verus-lang/verus/discussions/385

**Comment by utaal** [comment]
I did ask @marshtompsxd to open a discussion on this, forgetting that #385 was already/still open. Thanks @jaybosamiya for pointing it out. Closing this as a feature already being consider in #385.
