### ISSUE TITLE
`broadcast use _;` is not supported in the `calc!` macro

### ISSUE THREAD

**Issue by utaal** [verus-lang/verus#1088]
and it's often needed there.

cc @jaylorch

**Comment by jaybosamiya** [comment]
Fwiw, I have an _almost_ fully working re-implementation of `calc` that I hope to make a PR for soon (fingers crossed, if I can make the time, by tomorrow). It should improve a bunch of things about `calc` (including parsing, support for features, cleaner error messages, and such).

If you have a short example I can test with, I can try to make sure that the re-implementation supports that too.
