### ISSUE TITLE
Subtraits with Associate types trigger ownership checking failure

### ISSUE THREAD

**Issue by y1ca1** [verus-lang/verus#1098]
Minimal example:

```rust
use vstd::prelude::*;
verus! {
  trait A { type T; }
  trait B : A { type U; }
}
```
produces:
```sh
error: cannot find type `A23_Self` in this scope

error: aborting due to 1 previous error

note: This error was found in Verus pass: ownership checking of tracked code

error: aborting due to 2 previous errors
```

[Link to code](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=b9cffe478bb584201f339def182e196f)

**Comment by gancherj** [comment]
FYI after running the above code through `verus --log-all`, we get the ill-scoped code emitted by Verus for lifetime checking:
```
trait T24_A {
    type A2_T;
}

trait T26_B where A23_Self: T24_A,  {
    type A25_U;
}
```

**Comment by Chris-Hawblitzel** [comment]
I think this got fixed as part of https://github.com/verus-lang/verus/commit/f880ccf7bdb97a4f015d7a3de59abd4d5424dff2 .
