### ISSUE TITLE
Invalid AIR generation when returning unit type

### ISSUE THREAD

**Issue by pratapsingh1729** [verus-lang/verus#1108]
The following code:
```
use vstd::prelude::*;

verus! {

pub fn owl_unit() -> (res: ())
    ensures res == ()
{ () }

fn main() {
    owl_unit()
}

}
```
panics the verifier, as follows:
```
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:728:21:
internal error: generated ill-typed AIR code: error 'in call to ens%main!owl_unit., expected 2 arguments, found 1 arguments' in expression '(ens%main!owl_unit. 0)'
note: [run with `RUST_BACKTRACE=1` environment variable to display a backtrace](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021#)
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:339:17:
dropped, expected call to `into_inner` instead
stack backtrace:
...
```
[Minimal playground link with full backtrace](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=8a7fbc93d90dc20d79607c7d4957dae9)

On the other hand, removing the `ensures res == ()` on `owl_unit()` makes the panic go away ([link](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=277c4b487712b6c31225a5caad150719)).

Thanks to parametricity, the `ensures res == ()` spec is not actually needed, but noting in case it points to a bigger bug.

**Comment by Chris-Hawblitzel** [comment]
I'm adding other cases to this issue where using a unit return type can result in invalid AIR code.  For example (from https://github.com/verus-lang/verus/issues/1161 ):

```
trait T {
    spec fn f();
}

spec fn f<A: T>() {
    A::f()
}
```

**Comment by tjhance** [comment]
Here's another one:

```rust
trait Tr : Sized {
    fn get() -> (r: Self)
        ensures r == r;
}

impl Tr for () {
    fn get() -> (r: Self)
    {
    }
}
```

**Comment by tjhance** [comment]
With PR https://github.com/verus-lang/verus/pull/1280, all issues mentioned in this thread so far will be fixed, with the exception of:

```
trait T {
    spec fn f();
}

spec fn f<A: T>() {
    A::f()
}
```

This is a poly issue, so should be revisited after the upcoming poly refactor.
