### ISSUE TITLE
Convert `_auto` lemmas to `broadcast` lemmas in bitwise mask properties

### ISSUE THREAD

**Issue by utaal** [verus-lang/verus#1118]
https://github.com/verus-lang/verus/commit/78438925a7ffc9b6c0ac65c0f66c0be3ea981b78 introduced a number of `_auto` lemmas that should probably be `broadcast` lemmas instead. We may want to make that change soon, to avoid breaking more dependencies on the `_auto` lemmas if more users reference these.

cc @mmcloughlin @parno

**Comment by mmcloughlin** [comment]
Sorry about that. I'll take a look.

**Comment by mmcloughlin** [comment]
@utaal @parno please take a look at #1119. Thanks!

**Comment by mmcloughlin** [comment]
See also #1120 for similar changes in the `power2` module.
