### ISSUE TITLE
Issue when importing default impl methods across crates

### ISSUE THREAD

**Issue by pratapsingh1729** [verus-lang/verus#1147]
Suppose I have the following code (minimized from a much larger example):
```
use vstd::prelude::*;

verus! {

pub trait Foo {
    fn a(&self) -> (res: usize)
        ensures res < 10
    ;
    
    fn b(&self) -> (res: usize) 
        ensures res < 11
    {
        let x = self.a();
        x + 1
    }
}


struct Bar;

impl Foo for Bar {
    fn a(&self) -> (res: usize) {
        5
    }
}


fn main() {
    let x = Bar;
    let y = x.a();
    let z = x.b();

    assert(y < 10);
    assert(z < 11);
}

}
```

The key feature of interest in this code is the trait method `Foo:b`, which has a default implementation. The above code verifies just fine ([playground link](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=9965ab0f8130c09136ee3e449fe7dbe8)).

Now, however, suppose I split the above code into two crates: `crate_a`, a library crate containing the definition of `pub trait Foo`; and `crate_b`, a crate containing the definition of `struct Bar`, `impl Foo for Bar`, and `fn main()`. I use the `--export` and `--import` features to import the Verus definitions from `crate_a` into `crate_b`, during verification:

```
cd path/to/crate_a
verus --crate-type=lib src/lib.rs --compile --export crate_a.verusdata       
cd path/to/crate_b
verus src/main.rs --extern crate_a=path/to/crate_a/libcrate_a.rlib --import crate_a=path/to/crate_a/crate_a.verusdata
```

This gives me the following error:
```
error: `main::impl&%0%default%b` is not supported (note: you may be able to add a Verus specification to this function with the `external_fn_specification` attribute)
  --> src/main.rs:22:13
   |
22 |     let z = x.b();
   |             ^^^^^
```

Notably, calling `x.a()` from `crate_b` works just fine and verifies, which makes me think there is something specifically wrong with exporting and importing trait default methods. 

I made a reproducing example here: 
[verus-trait-default-issue.zip](https://github.com/verus-lang/verus/files/15494497/verus-trait-default-issue.zip).
The script `reproduce_issue.sh` should reproduce the error, assuming you have `verus` on your PATH.

Tested with verus version:
```
Verus
  Version: 0.2024.05.29.8e24346
  Profile: release
  Platform: linux_x86_64
  Toolchain: 1.76.0-x86_64-unknown-linux-gnu
```
but the issue also arose with a slightly older version (from about 5/24).

**Comment by Chris-Hawblitzel** [comment]
Thanks for the detailed minimized error report.  Can you try it now, with https://github.com/verus-lang/verus/commit/8f5166fb956f61279ccad0008564b8c2cc65c05e ?

**Comment by pratapsingh1729** [comment]
I tried with the latest Verus (0.2024.06.03.8f5166f) and indeed this issue is fixed. Thanks very much for the fix!
