### ISSUE TITLE
trait default spec fns stopped working

### ISSUE THREAD

**Issue by jonhnet** [verus-lang/verus#1157]
In this reduced example, Trait::foo has a default body. Struct::test can't see that definition. If we copy the default body of `foo` into the `impl Trait for Struct` (commented out below), the verification succeeds.

```rust
use builtin_macros::*;

verus! {

pub trait Trait {
    spec fn hidden(&self) -> bool
        ;

    open spec fn foo(&self) -> bool
    {
        self.hidden()
    }

    proof fn test(&self);
}

pub struct Struct {
}

impl Trait for Struct {
    open spec fn hidden(&self) -> bool
    {
        true
    }

//     open spec fn foo(&self) -> bool
//     {
//         self.hidden()
//     }

    proof fn test(&self) {
        assert(self.foo() == self.hidden());
    }
}

}
```

[2024-06-06-11-56-10.zip](https://github.com/user-attachments/files/15679809/2024-06-06-11-56-10.zip)

(severity: I can work around this with a tedious degree of copy-pasting.)

**Comment by jonhnet** [comment]
Here is a perhaps-related issue: it's not about a trait default, but it's another case of an `open spec fn`'s definition suddenly being unavailable in a proof. In this recording, the first two assertion failures on 441 & 443:

[2024-06-06-14-32-31.zip](https://github.com/user-attachments/files/15686653/2024-06-06-14-32-31.zip)

**Comment by jonhnet** [comment]
Okay, I think some sort of triggering plumbing went really haywire. Here's another very weird behavior (that happens to be in a trait impl): `exec_set` has a postcondition in the trait. I can assert that postcondition at the end of the impl, but I still get the `postcondition not satisfied` error. I can even add it as an additional `ensures` on the impl fn, and that ensures works, but the ensures declared on the trait still fails.

I'm pretty sure this is a Verus bug because if there's one thing I should be able to in a Dafny/Verus-like language, it's copy a failing postcondition into an assert/assume and make the postcondition error disappear.

[2024-06-06-18-01-31.zip](https://github.com/user-attachments/files/15688322/2024-06-06-18-01-31.zip)

**Comment by Chris-Hawblitzel** [comment]
Can you try with the latest commit?

**Comment by Chris-Hawblitzel** [comment]
I'll address the second problem separately.  Here's a minimized repro:

```
trait T {
    spec fn f() -> int;
}

struct S<A>(A);

impl<A: T> T for S<A> {
    spec fn f() -> int { 3 }
}

trait U {
    type X: T;
}

proof fn test2<Z: U>() {
    assert(<S<Z::X> as T>::f() == 3);
}
```

I suspect that the trait bound axiom for `X: T` is missing.

**Comment by Chris-Hawblitzel** [comment]
Ok, the second problem should be fixed too.

**Comment by jonhnet** [comment]
Thanks for your speedy work! I just tried at the current main commit 78a7e67, and got a panic:

```rust
+ /home/jonh/verus/source/target-verus/release/verus --time src/marshalling_test.rs
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:522:17:
internal error: ill-typed AIR code: error 'error 'use of undeclared function proj%%marshalling_test!marshalling.Marshalling_v.Marshal./U' in expression '(proj%%marshalling_test!marshalling.Marshalling_v.Marshal./U Self%&. Self%&)'' in expression '(tr_bound%marshalling_test!marshalling.Marshalling_v.Deepview. (proj%%marshalling_test!marshalling.Marshalling_v.Marshal./U
  Self%&. Self%&
 ) (proj%marshalling_test!marshalling.Marshalling_v.Marshal./U Self%&. Self%&) (proj%%marshalling_test!marshalling.Marshalling_v.Marshal./DV
  Self%&. Self%&
 ) (proj%marshalling_test!marshalling.Marshalling_v.Marshal./DV Self%&. Self%&)
)'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:1950:29:
```

[2024-06-07-20-09-51.zip](https://github.com/user-attachments/files/15746292/2024-06-07-20-09-51.zip)

**Comment by Chris-Hawblitzel** [comment]
Can you try now?

**Comment by jonhnet** [comment]
Nice! I just tried commit `d1c6065`: No panic, and I was able to delete all the workarounds in my code that I had marked 'issue 1157'. Things seem much happier now. _Thank you!_
