### ISSUE TITLE
Definitions of functions mentioned in trait requires/ensures are not always visible to implementations of that trait

### ISSUE THREAD

**Issue by jonhnet** [verus-lang/verus#1235]
In this recording, introducing IntegerMarshalling_v.rs:63 causes proofs of a *different* obligation `deepv_is_as_int` to fail in the trait implementations (lines 146, 207). Commenting out line 63 (replacing it with 62: `assume(false)`) hides the problem. This is weird, because the line causing the problem is a *call* to the function whose impl proofs break. I conjecture this is some strange interaction with how trait defaults are encoded?

[2024-07-25-09-35-43.zip](https://github.com/user-attachments/files/16381187/2024-07-25-09-35-43.zip)

**Comment by Chris-Hawblitzel** [comment]
@jonhnet Can you try https://github.com/verus-lang/verus/tree/trait-req-ens-call-graph ?

**Comment by jonhnet** [comment]
Yep, that fixes the case captured in this zip! Lovely!
My guess that #1239 was related to this #1235 turns out to be wrong, though.

**Comment by Chris-Hawblitzel** [comment]
Fixed by https://github.com/verus-lang/verus/commit/33269ac6a0ea33a08109eefe5016c1fdd0ce9fbd
