### ISSUE TITLE
Array verification regression

### ISSUE THREAD

**Issue by tjhance** [verus-lang/verus#1236]
This wrongly fails to verify:

```
struct X { }

fn test2<'a>(p: &'a Option<[X; 75]>) -> (res: &'a [X; 75])
    requires p.is_some()
    ensures 
        Some(*res) == p
{
    p.as_ref().unwrap()
}
```

Seems to be a regression from 2ab19dad5b58b6f4daa20c4331f2a26ddaec92b3.

**Comment by y1ca1** [comment]
Not sure if it's the same issue:

```rs
fn main() {
    let a1 = [1, 2, 3];
    let a2 = [1, 2, 5];

    assert(a1 != a2); // ok
    assert(a1@ != a2@); // fails to verify
}
```

[Link to code](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=62367e2031ae8bcced5e05dc0cfd5112)

**Comment by tjhance** [comment]
BTW, this issue currently causes verus-memory-allocator to fail verification, so I'm adding the 'blocking' label.

Not sure about @y1ca1's issue. In fact, I'm not sure if it ever worked.

**Comment by y1ca1** [comment]
> Not sure about @y1ca1's issue. In fact, I'm not sure if it ever worked.

I just tried it with:

```sh
❯ verus --version
Verus
  Version: 0.2024.07.15.6e30b8a
  Profile: release
  Platform: macos_aarch64
  Toolchain: 1.76.0-aarch64-apple-darwin
```

So the same code worked on 6e30b8a8ab1452f5b3a346e1a9388939b2a77bbb.

**Comment by Chris-Hawblitzel** [comment]
> ```rust
> fn main() {
>     let a1 = [1, 2, 3];
>     let a2 = [1, 2, 5];
> 
>     assert(a1 != a2); // ok
>     assert(a1@ != a2@); // fails to verify
> }
> ```

I believe this is a separate issue.  I just pushed a fix for this (although it does not fix the original issue that @tjhance reported).  @parno you might want to merge the latest commit into https://github.com/verus-lang/verus/tree/seq-to-array -- it should make it easier to verify code that uses `seq!`.

**Comment by parno** [comment]
Cool, thanks for the tip, and for the fix to this issue.
