### ISSUE TITLE
Using `PhantomData` will cause an unnecessary inaccessible fields error

### ISSUE THREAD

**Issue by chrihop** [verus-lang/verus#1242]
`PhantomData` is declared as the `verifier::external_type_specification` of `ExPhantomData` in module `vstd::std_spec::core`. Using `PhantomData` for any purpose will cause an error stating: "a datatype is treated as opaque whenever at least one field is not visible". The error makes no sense since`PhantomData` has no field.

Please see the sample code posted in the [verus playground](
https://play.verus-lang.org/?version=stable&mode=detailed&edition=2021&gist=0a0c17e2e2b01c617e11bc7f99bf4589).

**Comment by tjhance** [comment]
Indeed, the error message is wrong - PhantomData is not opaque because of visibility, it's opaque because it's marked `external_body` when it's imported in vstd.

TODO:

 - [ ] fix error message
 - [ ] make PhantomData not external_body

**Comment by tjhance** [comment]
PhantomData constructors should now work (e0c7fef6371a9f46ac0dc5d5dbe4bbf98125b0d7)

**Comment by tjhance** [comment]
PhantomData constructors should now work (a632e50fa73984fe697bd608f71fd0e8bd133275)

**Comment by chrihop** [comment]
It works well! Thank you for fixing it!
