### ISSUE TITLE
Verification fails, but succeeds with `--verify-function`

### ISSUE THREAD

**Issue by jaylorch** [verus-lang/verus#1269]
In the attached two .zip files generated by running with `--record`, the first run finds a verification failure in `abort_after_failed_item_table_tentatively_write_item`, namely a failure to satisfy a precondition of a lemma. But in the second run, using `--verify-function abort_after_failed_item_table_tentatively_write_item`, it reports "1 verified, 0 errors".
[2024-09-18-11-56-53.zip](https://github.com/user-attachments/files/17049668/2024-09-18-11-56-53.zip)
[2024-09-18-11-58-15.zip](https://github.com/user-attachments/files/17049672/2024-09-18-11-58-15.zip)

**Comment by jaylorch** [comment]
I've been informed that the `--record` didn't capture this important file:
[libdeps_hack.zip](https://github.com/user-attachments/files/17050225/libdeps_hack.zip)

**Comment by jaylorch** [comment]
And here's the entirety of deps_hack/target/release:
[deps_hack_target_release.zip](https://github.com/user-attachments/files/17050630/deps_hack_target_release.zip)

**Comment by jaylorch** [comment]
Here are the SMT files generated: 
[verify_function_kv__durable__durableimpl_v.smt2.zip](https://github.com/user-attachments/files/17051034/verify_function_kv__durable__durableimpl_v.smt2.zip)
[verify_module_kv__durable__durableimpl_v.smt2.zip](https://github.com/user-attachments/files/17051035/verify_module_kv__durable__durableimpl_v.smt2.zip)

**Comment by jaylorch** [comment]
If you want to build `deps_hack` yourself, you can use the `kv_dev` branch of https://github.com/microsoft/verified-storage

**Comment by yizhou7** [comment]
I am somewhat confused about the smt2 log output.  For the module version of the query,
line 58398--59621 seems to contain the query for `abort_after_failed_item_table_tentatively_write_item`. 
```
;; Function-Def lib::kv::durable::durableimpl_v::DurableKvStore::abort_after_failed_item_table_tentatively_write_item
;; c:/Apps/verified-storage-windows/storage_node/src\kv\durable\durableimpl_v.rs:2500:9: 2504:10 (#0)
```
However, the corresponding `check-sat` at 59619 is not followed by `get-model` or more `check-sat` for debugging. 
In other words, that `check-sat` at 59619 seemed to have worked according to the smt2 log. 
I ran Mariposa on both queries and they both turn out to be stable. 
Maybe I am misunderstanding something here?

**Comment by jaylorch** [comment]
Oh, I was apparently confused about where the errors were. Sorry about that!
