### ISSUE TITLE
std_specs's result type cannot infer Ok / Err from the extracted value

### ISSUE THREAD

**Issue by zpzigi754** [verus-lang/verus#1270]
I tried the below code with the latest verus.

```
use vstd::prelude::*;

verus! {

pub enum Err {
    Error
}

proof fn test_err(ret: Result<(), Err>)     
{   
    assert(ret.get_Err_0() == Err::Error ==> ret.is_Err());
}   

proof fn test_ok(ret: Result<(), Err>)     
{
    assert(ret.get_Ok_0() == () ==> ret.is_Ok());
}

fn main() {
}   

} 
```

The verification has failed with the following messages.
```
./target-verus/release/verus --compile rust_verify/example/result.rs 
error: assertion failed
  --> rust_verify/example/result.rs:11:12
   |
11 |     assert(ret.get_Err_0() == Err::Error ==> ret.is_Err());
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ assertion failed

error: assertion failed
  --> rust_verify/example/result.rs:16:12
   |
16 |     assert(ret.get_Ok_0() == () ==> ret.is_Ok());
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ assertion failed

error: aborting due to 2 previous errors

verification results:: 1 verified, 2 errors
```

I think that if `get_Err_0()` as well as `get_Ok_0()` have succeeded, verus should be able to infer their corresponding result variant (ret.is_Err() or ret.is_Ok()).

One workaround would be adding the below lemma in `std_specs/result.rs`, but it might be rather inconvenient to use, as it needs to pass the value whenever the case is encountered. 
```
proof fn lemma_get_err_imply_err(&self, err: E)
    ensures self.get_Err_0() == err ==> self.is_Err()
{
     admit();
}
```

**Comment by tjhance** [comment]
In Verus, all functions are total, including `ret.get_Ok_0()`. This means that even if `ret` is an `Err`, `ret.get_Ok_0()` will be a valid unit value. In fact, it will have to be `()`, which is the only valid unit value.

Therefore, `self.get_Ok_0() == () ==> self.is_Ok()` isn't true, and in fact, it's unsound.

Instead of writing `self.get_Ok_0() == ()`, I suggest writing `self == Ok(())`.

**Comment by zpzigi754** [comment]
Thank you for the detailed explanation and correction! It sounds a bit weird though (if `ret` is an `Err`, `ret.get_Ok_0()` will be a valid unit value), because extracting Ok's inner value when ret is an Err should be unreachable by a panic in terms of rust's semantic.
