### ISSUE TITLE
Verus crashes on startup trying to allocate too much memory

### ISSUE THREAD

**Issue by dschoepe** [verus-lang/verus#1294]
[2024-10-01-13-51-30.zip](https://github.com/user-attachments/files/17216363/2024-10-01-13-51-30.zip)
Verus fails with message `memory allocation of 5952326319994162 bytes failed` (note that this is trying to allocate >5PB) on an empty example file containing only an import and an empty `verus!` block (and any file I tried containing additional code). Archive produced by `--record` is attached. This happens with both debug and release builds. This is the piece of code it fails on:

```
use vstd::prelude::*;

verus! {

}

```

The bug doesn't occur with the previous commit (`25303cd2eabd3c16aa6e5302e18272acbf51c660`).

**Comment by parno** [comment]
Huh, that's very strange behavior!  It sounds like you're using Verus commit `3c05f3cbe6`, right?  When I try it on the example file in your report, I see the expected:
```
$ verus github-1294/example.rs                     [3c05f3cb] 
error[E0601]: `main` function not found in crate `example`
 --> github-1294/example.rs:5:2
  |
5 | }
  |  ^ consider adding a `main` function to `github-1294/example.rs`

error: aborting due to 1 previous error
```
and if I add the appropriate flag, I see:
```
$ verus --crate-type=lib github-1294/example.rs    [3c05f3cb] 
verification results:: 0 verified, 0 errors
```
This is on macOS Sonoma 14.4.1.  

Do you mind sharing more about your setup?

**Comment by dschoepe** [comment]
I think I didn't rebuild all the verus components correctly (running `vargo build -p verus` rather than just `vargo build`). The issue disappeared after a proper rebuild

**Comment by parno** [comment]
Okay, glad to hear you found a simple resolution!

**Comment by rsofaer** [comment]
I got this error on Verus commit da26059 and running `cargo clean` on the repository I was building moved me past it.

**Comment by utaal** [comment]
This happens when we try and load (I think) the VIR bundle for vstd for an outdated version of Verus, confusing the deserializer. We should probably find a way to catch the format mismatch before we try and load it.
