### ISSUE TITLE
Panic asserting `call_ensures` about `clone`

### ISSUE THREAD

**Issue by hayley-leblanc** [verus-lang/verus#1332]
I'm attempting to write some proofs to reason about the equality of certain cloned objects. I'm using `call_ensures` based on some discussion with Chris and also a few messages about using it to reason about `clone` and `eq` in Zulip but this seems to be causing a panic in Verus.

Here's a minimal code snippet that reproduces the bug. I've found that `assert(forall |a: Self, b: Self| call_ensures(Clone::clone, (&a,), b) ==> a == b)` also causes the panic,  but including it as a postcondition of an associated proof function in a trait definition is fine (until I attempt to provide an implementation for the proof). 
```
#[derive(Copy, Clone, Debug)]
pub struct Foo {
    val: u64,
}

impl Foo {
    proof fn lemma_clone() 
        ensures 
            forall |a: Self, b: Self| call_ensures(Clone::clone, (&a,), b) ==> a == b,
    { assume(false); }
}
```
The error message is:
```
thread '<unnamed>' panicked at vir/src/datatype_to_air.rs:740:42:
expected fndef function in pruned crate
note: [run with `RUST_BACKTRACE=1` environment variable to display a backtrace](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=0a9afd2f5757d05349df8857af6d7b5f#)
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:2123:29:
worker thread panicked
```

(Playground link: https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=0a9afd2f5757d05349df8857af6d7b5f) 

My local Verus version:
```
Verus
  Version: 0.2024.10.31.141c73e
  Profile: release
  Platform: linux_x86_64
  Toolchain: 1.79.0-x86_64-unknown-linux-gnu
```

**Comment by tjhance** [comment]
Currently, the recommended way to do this is:

```
#[verifier::external_fn_specification]
pub fn ex_foo_clone(b: &Foo) -> (res: Foo)
    ensures
        res == b,
{
    b.clone()
}
```

The reason for the panic is that Verus doesn't recognize the `Clone` trait implementation, probably because the derive(Clone) macro doesn't add the verus_macro to it. I'm not sure why it's a panic instead of a normal error; I need to look into that more.

**Comment by tjhance** [comment]
Commit https://github.com/verus-lang/verus/commit/84ca82146bbfd836a3b18488d63a249071b45ef4 fixes the panic to a normal error message.
