### ISSUE TITLE
Can't prove `let c = a && b; assert(c == a && b);`

### ISSUE THREAD

**Issue by zhengyao-lin** [verus-lang/verus#1336]
This snippet doesn't work
```
use vstd::prelude::*;

verus! {

fn test(a: bool, b: bool) {
    let c = a && b;
    assert(c == a && b);
}

}
```
It works for `||` though.

Playground link: https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=9009884b3a5200f59c6f3ff419e57aed

**Comment by parno** [comment]
This seems to be a bug (or at least a surprise) w.r.t. order of operations/precedence.  If you try
```
assert(c == (a && b));
```
it works as expected.

**Comment by tjhance** [comment]
This is the intended operator precedence, also consistent with rust.

**Comment by zhengyao-lin** [comment]
lol sorry I need more coffee
