### ISSUE TITLE
Verus doesn't support recursive `struct` or `enum`

### ISSUE THREAD

**Issue by rifatarefin** [verus-lang/verus#1360]
Consider this enum,
```
 enum  itemList {
  item1 {val: i32, next: Box<itemList>},
  item2 {name: char, next: Box<itemList>}
 }
```
Verus raises error: `datatype must have at least one non-recursive variant`. This is a valid rust code, using `Box<>` makes the enum size fixed. The same error populates for recursive structs as well.
```
struct MyStruct {
  val: i32, next: Box<MyStruct>
}
```
This is the `verus --version` output on my system:

```
Verus
  Version: 0.2024.12.02.12b857f
  Profile: release
  Platform: macos_aarch64
  Toolchain: 1.79.0-aarch64-apple-darwin
```

**Comment by tjhance** [comment]
These type declarations are technically allowed, but they aren't very useful since they can't be constructed. Verus also doesn't support empty enums (though I believe we have _ad hoc_ support the never type, `!`).

Do you have a specific use case in mind that Verus is currently preventing?

**Comment by rifatarefin** [comment]
These can be constructed if we use `Option` like this:
```
enum  itemList {
  item1 {val: i32, next: Box<Option<itemList>>},
  item2 {name: char, next: Box<Option<itemList>>}
 }
```
This is allowed in Rust (and Dafny also). I was wondering if the same could be done with Verus.

**Comment by parno** [comment]
If you add the `Option`, then Verus also [happily accepts this definition](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=d13cb058972fe9e97591b7619036301e).

**Comment by tjhance** [comment]
I do think there might be some useful types that are ruled out by an over-conservative analysis, but I haven't personally run into any, and as Bryan says, a recursive type that uses an Option is perfectly fine.

If you do encounter such a type, feel free to let us know. Otherwise, I'm going to close the issue.
