### ISSUE TITLE
unimplemented inside trait function causes panic

### ISSUE THREAD

**Issue by arsene1995** [verus-lang/verus#1369]
Hi, 

The following code seems to cause Verus to panic.
Once I comment out the "unimplemented!()", Verus succeeds.

Here is the verus --record zip
[2024-12-20-14-16-30.zip](https://github.com/user-attachments/files/18215917/2024-12-20-14-16-30.zip)

```
use builtin_macros::*;

verus! {

  pub fn main()
  {
  }

  pub trait Foo {

    #[verifier::external_body]
    fn fun ()
    {
      unimplemented!()
    }
  }
}
```

**Comment by arsene1995** [comment]
ok... I realized that inside pub trait, I shouldn't have implemented anything, so that "unimplemented!()" should not have been there ... 
I just didn't expect that error message ...

**Comment by tjhance** [comment]
this is definitely a bug, I'm going to reopen the issue

**Comment by tjhance** [comment]
Well, actually, I'm unable to reproduce the problem. So I'm going to close it again.

In general, though, anything that causes Verus to 'panic' could reasonably be considered a bug.

**Comment by arsene1995** [comment]
hmmm, indeed, it doesn't crash on Verus playground.
I guess that is because my local Verus is an old version? ...
In any case, thank you @tjhance
