### ISSUE TITLE
Questions on set equality check

### ISSUE THREAD

**Issue by marshtompsxd** [verus-lang/verus#189]
Hi Verus team,

We encountered some problems when checking the equality of set:
```
    #[spec] let s1: Set<i32> = Set::empty().insert(1);
    #[spec] let s2: Set<i32> = Set::empty();
    assert(!equal(s1, s2));
```
The assertion fails though s1 and s2 are not the same.
If we change `assert(!equal(s1, s2));` to `assert(equal(s1, s2));`, the assertion still fails.
Is it expected behavior or a bug?
(BTW, if I add `assert(!s2.contains(1));` before the last assertion then it will pass.)

This concerns us because we have some predicates like
```
#[spec] #[verifier(publish)]
pub fn next(s1: Set, s2: Set, v, ...) -> bool {
    ...
    && equal(s1.insert(v), s2)
}
```
And we want to prove that `exists` some s1, s2 so that next(...) is true. If Verus cannot tell whether two sets are equal or not, is it possible that the `exists` is always false even if there actually are some s1 and s2 which make next() true?

**Comment by marshtompsxd** [comment]
I also tried
```
    #[spec] let s1: Set<i32> = Set::empty().insert(1);

    assert(exists(|s3: Set<i32>| !equal(s3, s1)));
```
and it says
```
error: Could not automatically infer triggers for this quantifer.  Use #[trigger] annotations to manually mark trigger terms instead.
   --> ../../mini-controller/src/spec/network_test.rs:138:12
    |
138 |     assert(exists(|s3: Set<i32>| !equal(s3, s1)));
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by utaal** [comment]
For your second comment, our guess is that's not something you'll need to write in actual spec, or can write as, e.g., a lemma returning two specific different sets (let us know if that's not the case).

The reason you cannot write that quantifier is that Z3 does not support quantifier triggers ("patterns") on equality.

If you really need to write that quantifier, you can do:

```
        spec fn different_set<V>(s: Set<V>) -> Set<V> { s }

        proof fn test_sets_1() {
            let s1: Set<i32> = Set::empty().insert(1);

            assert (exists|s3: Set<i32>| different_set(s3) !== s1) by {
                assert(!different_set(Set::empty()).contains(1));
            }
        }
```

where `different_set` ends up being the trigger you need to mention whenever you try and use that fact.

**Comment by utaal** [comment]
Let me know if you have further questions about this.

**Comment by marshtompsxd** [comment]
Hello @utaal , thank you so much for your replies!

I have one more question regarding proof by induction.
Let's say I have a predicate like:
```
// next checks the equality of two sets
pub fn next(c: MyConstants, v: MyVariables, v_prime: MyVariables) -> bool {
    ...
    && equal(v.s.insert(v), v_prime.s) // s is a Set
}
```
and I will use them in a precondition like
```
fn inv_inductive(c: MyConstants, v: MyVariables, v_prime: MyVariables) {
    requires(inv(c, v) && next(c, v, v_prime)); // inv is another predicate
    ensures(inv(c, v_prime));
}
```

If I just write the precondition without additional proof, will Verus always assume the precondition is false? And do I need to provide any additional proofs to let Verus know that there exists `v` and `v_prime` so that `equal(v.s.insert(v), v_prime.s)` is true? If so, how should I do it when it is in precondition and there is no concrete `v` and `v_prime` here? 

Or does Verus just automatically assume `v` and `v_prime` can make `next` true in this function even without any witeness?

**Comment by utaal** [comment]
Resolved offline.
