### ISSUE TITLE
Field visibility of structs with both private and pub fields

### ISSUE THREAD

**Issue by ziqiaozhou** [verus-lang/verus#221]
@utaal @Chris-Hawblitzel 
I am not sure whether this is a potential bug or a feature missing. 

In struct.rs
``` 
pub struct TestStruct {
    pub val0: u8,
    val1: u8,
}

impl TestStruct{
    pub fn new()-> Self
    {
        TestStruct{val0: 0, val1: 1}
    }

}


```

In main.rs
```
pub mod struct;
use struct::*;

fn main() {
    let test_struct = TestStruct::new();
    let y= test_struct.val0;
}
```

-------------------

* generic rust compiler compiles it without errors.
* verus will raise error due to inaccessible fields (but val0 should be public);
```
error: field access of datatype with inaccessible fields here
 --> rust_verify/example/main.rs:6:12
  |
6 |     let y= test_struct.val0;
  |            ^^^^^^^^^^^^^
```

* verus works only if I make all fields public in TestStruct 
``` 
pub struct TestStruct {
    pub val0: u8,
    pub val1: u8,
}
```

**Comment by utaal** [comment]
This is somewhat intentional at this stage, due to the increased complexity of implementing support for this and the fact that we'd like to encourage users to have clear abstraction boundaries, as they also can help with reducing the number of verification conditions that are unnecessarily made public and may slow down verification.

Do you have a specific use case for which you'd like to use this?

**Comment by tjhance** [comment]
We can probably update the error message with a little more information, e.g., "note: Verus currently treats a datatype as opaque whenever at least one field is not visible"

**Comment by Chris-Hawblitzel** [comment]
I think we can eventually support a mixture of public and private fields.  It may be a while before one of us gets around to implementing it.  One possible workaround in the meantime is to use all private fields with public getter and setter methods.

**Comment by utaal** [comment]
> We can probably update the error message with a little more information, e.g., "note: Verus currently treats a datatype as opaque whenever at least one field is not visible"

Addressed with https://github.com/secure-foundations/verus/commit/211fddb230d423081b7b433896ef9c7d227f34d4

**Comment by utaal** [comment]
As the error message is now more informative and there's a workaround, I'll close this. Please reopen if this becomes a blocker.
