### ISSUE TITLE
Compiler panics when calling spec function in `external_body` exec function

### ISSUE THREAD

**Issue by matthias-brun** [verus-lang/verus#257]
```rust
use builtin_macros::*;

verus! {

#[verifier(external_body)]
fn f(x: usize) -> usize {
    id(x)
}

pub open spec fn id(x: usize) -> usize {
    x
}

fn main() {
}

}

```

```
fhs m: source 1 ν ./tools/rust-verify.sh /st/verus/test.rs
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /st/verus/verif/verus/rust/compiler/rustc_middle/src/hir/map/mod.rs:210:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by tjhance** [comment]
The body of an 'external_body' function needs to be purely ordinary rust code, that is, exec code. Here, 'id' is a spec function, so that code is not compilable.

**Comment by matthias-brun** [comment]
Thanks for pointing that out; yes, the code is invalid. But the panic makes it harder than necessary to locate the error. There should be an error message instead. (I called the spec function by accident, thinking it was exec mode.)

**Comment by utaal** [comment]
This panic was fixed as a side effect to the move to macro-based erasure. We do not emit an error or warning if the spec function is public, as its signature will appear in the final `rlib`, with a body that panics, so dependent crates can refer to it. It is difficult to prevent this, as we don't interpret the `#[verifier(external_body)]` functions.

**Comment by utaal** [comment]
I added a regression test.
