### ISSUE TITLE
Panic in erasure when using unnecessary parentheses

### ISSUE THREAD

**Issue by matthias-brun** [verus-lang/verus#260]
This appears to be an erasure bug so it should go away once we move to mainline rust. Posting here in case anyone else runs into this.

```rust
use builtin_macros::*;

verus! {

fn f() {
    let (x):usize = 0;
}

fn main() {
}
}
```
results in
```
fhs m: source 101 ν ./tools/rust-verify.sh /st/verus/test.rs
warning: unnecessary parentheses around pattern
 --> /st/verus/test.rs:6:9
  |
6 |     let (x):usize = 0;
  |         ^ ^
  |
  = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
  |
6 -     let (x):usize = 0;
6 +     let x:usize = 0;
  |

thread 'rustc' panicked at 'internal error: could not find span /st/verus/test.rs:6:9: 6:12 (#12)', rust_verify/src/erase.rs:177:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The warning gives a hint as to where the issue is but I had this happen in a function where I added `#[allow(unused_parens)]` due to #230, so it took me quite a while to track down the problem.

**Comment by tjhance** [comment]
I'm gonna go ahead and close this since we're moving to the new erasure. I added a test, though (21c592788777e354b6ddb69fd642610186124923)
