### ISSUE TITLE
Rust to VIR doesn't respect hygienic identifiers

### ISSUE THREAD

**Issue by utaal** [verus-lang/verus#279]
Identifiers with the same name should be considered distinct if they originate from a macro expansion.

For example, in:

```rust
#[macro_export]
#[doc(hidden)]
macro_rules! assert_sets_equal_internal {
    ($s1:expr, $s2:expr $(,)?) => {
        assert_sets_equal_internal!($s1, $s2, elem => { })
    };
    ($s1:expr, $s2:expr, $elem:ident $( : $t:ty )? => $bblock:block) => {
        let s1 = $crate::pervasive::set_lib::check_argument_is_set($s1);
        let s2 = $crate::pervasive::set_lib::check_argument_is_set($s2);
        ::builtin::assert_by(::builtin::equal(s1, s2), {
            ::builtin::assert_forall_by(|$elem $( : $t )?| {
                ::builtin::ensures(
                    ::builtin::imply(s1.contains($elem), s2.contains($elem))
                    &&
                    ::builtin::imply(s2.contains($elem), s1.contains($elem))
                );
                { $bblock }
            });
            $crate::pervasive::assert(s1.ext_equal(s2));
        });
    }
}
```

`s1` and `s2` maintain their user-visible name after expansion, but they are distinct from variables with the same name in the calling scope (due to macro hygiene). We don't handle this correctly, and treat them as synonyms of variables with the same name in the same scope, i.e. in case there is:

```rust
let s1: usize = 0;
let s2: usize = 0;
...
assert_sets_equal(...);
```

This may result in invalid AIR code (and maybe, potentially unsoundness?).

Originally found by @matthias-brun.

---

* [ ] un-ignore https://github.com/secure-foundations/verus/commit/b68f8e4bcd2ec3b7a5e1de2517fc7d69a9d07375

**Comment by utaal** [comment]
Minimized:

```rust
        macro_rules! assert_with_binding {
            ($s1:expr) => {
                let s1 = $s1;
                assert(s1);
            }
        }

        proof fn test() {
            let s1: nat = 0;
            assert_with_binding!(true);
            assert(s1 === 0);
        }
```

**Comment by tjhance** [comment]
I think we can use this HirID to disambiguate: https://doc.rust-lang.org/stable/nightly-rustc/rustc_hir/enum.PatKind.html#variant.Binding

One thing to watch out for though is that using HirIDs in the AIR identifiers might be counter to the goal of stable SMT queries and cause flaky proofs. One possibility would be to use the ItemLocalID part of the HirID (https://doc.rust-lang.org/stable/nightly-rustc/rustc_hir/hir_id/struct.HirId.html). Alternatively, we could manually track colliding variable names and use names like `a`, `a%0`, `a%1`, etc.
