### ISSUE TITLE
Using `ghost()` in spec mode should either be allowed or emit a better error message

### ISSUE THREAD

**Issue by matthias-brun** [verus-lang/verus#285]
Sometimes it's necessary to wrap types in `Ghost` inside spec code (e.g. to construct a struct with a ghost field). Using `ghost()` in spec code results in the error message `unexpected proof/ghost/tracked`.

One can just use `Ghost::new()` instead but this isn't easily discoverable. We should either change the error message to point out `Ghost::new()` to the user or alternatively directly allow `ghost()` to be used in spec mode.

**Comment by utaal** [comment]
Thanks! Moved to https://github.com/verus-lang/verus/wiki/Status:-feature-requests
