### ISSUE TITLE
Incomplete erase causing 'rustc' panicked at 'called `Option::unwrap()`

### ISSUE THREAD

**Issue by ziqiaozhou** [verus-lang/verus#293]
The cause of the bug is due to the incomplete erase of spec functions. 

I have a spec function called `valid_addr` in a module `utils`
I somehow use it in another module
```
use utils::valid_addr;
```

It finally throw out a panic in rustc 
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /root/snp/verus/rust/compiler/rustc_middle/src/hir/map/mod.rs:210:52
```

There is no hint about this bug and so I spend more time to figure it out by removing my change line by line.
It would be nice if verus team can add some early-stage checker to check this error or add a complete logic to erase spec 
import. Otherwise, it could be painful to find out the cause of the bug.

The bug disappears if I use `use utils::*;`

**Comment by tjhance** [comment]
Could you post a full example that reproduces the error?

**Comment by tjhance** [comment]
I tried the below, but it seems to work fine, so there must be something more to the error.

```rust
use builtin::*;
use builtin_macros::*;

verus!{

  mod X {
      pub closed spec fn foo();
  }

  use X::foo;

  proof fn some_proof_fn() {
      let x = foo();
  }

  fn main() { }

}
```

**Comment by ziqiaozhou** [comment]
```

```

**Comment by ziqiaozhou** [comment]
The sample code you tested also works from my side. It seems due to an additional annotation `#![allow(dead_code)]` I added to suppress some warning. 
```
#![allow(dead_code)] // Option 2: remove to fix
use builtin::*;
use builtin_macros::*;

verus!{

  mod X {
      pub open spec fn foo();
  }

  

  proof fn some_proof_fn() {
      let x = foo();
  }

  

}

use X::foo; // Option1: change to use X::* to fix

fn main() { }
```

You should got an error
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /root/snp/verus/rust/compiler/rustc_middle/src/hir/map/mod.rs:210:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by tjhance** [comment]
This is fixed with the new erasure mechanism. I added a test (c16e464ef41a9c3f40c21e1256cafbb9da5d3c6d).
