### ISSUE TITLE
Is `x === Option::None` the same as `x.is_None()` in spec/proof code?

### ISSUE THREAD

**Issue by marshtompsxd** [verus-lang/verus#299]
Hi Verus team,

I see there are many examples using `is_None`/`is_Some` for Option type but I didn't find their definition.
I am just wondering is `x===Option::None` exactly the same as `x.is_None()` when used in spec/proof code?

Besides, I find `get_Some_0` very handy. And I am wondering what would happen if we call it when x is actually None?
For example
```
if x.is_None() {
  x.get_Some_0() ...
}
```

**Comment by tjhance** [comment]
Yeah, x.is_None() is the same as x === None.

If x is None and you call get_Some_0() it just returns an arbitrary value.

**Comment by tjhance** [comment]
Just realized I missed one of your questions. 

These 2 functions are generated from the #[is_variant] attribute. You can apply it to any enum definition.
