### ISSUE TITLE
Verus crashes when returning closure type from a spec function

### ISSUE THREAD

**Issue by marshtompsxd** [verus-lang/verus#304]
Hi Verus team,

I am trying to write some spec functions that take a (spec) closure as a function parameter and return another (spec) closure, like
```
spec fn transform_foo (foo: impl Fn(Cat) -> bool) -> impl Fn(Seq<Cat>) -> bool {
    move |cats: Seq<Cat>| foo(cats[0])
}
```

However, Verus crashes with
```
thread 'rustc' panicked at 'The verifier does not yet support the following Rust feature: type impl Fn(pervasive::seq::Seq<apis::Cat>)-> bool', rust_verify/src/rust_to_vir_base.rs:318:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
verification results:: verified: 0 errors: 0
```
It seems to me that Verus cannot accept function return value being a closure.

**I am wondering what is the best way to write a spec function that takes a closure as an input parameter and also returns a closure?
Besides, is there a way to specify the closure as spec code?**

**Comment by tjhance** [comment]
This is something we'll hopefully fix soon - we're planning to add a type (not a trait) which can represents functions in spec-code. Then it will be possible to return a function type. (Although, in exec code, we will always be restricted by what Rust allows.)

In the meantime, my recommendation as a workaround would be to use a `Set`, e.g.,

```rust
spec fn transform_foo (foo: impl Fn(Cat) -> bool) -> Set<Seq<Cat>> {
    Set::new(|cats: Seq<Cat>| foo(cats[0]))
}
```

**Comment by marshtompsxd** [comment]
Thank you @tjhance !

**Comment by utaal** [comment]
Thanks for the report @marshtompsxd. I'm going to close this as a feature request for something that's planned. Feel free to re-open if you have other questions regarding this.
