### ISSUE TITLE
Triggers matched on out-of-context lemmas

### ISSUE THREAD

**Issue by zhengyao-lin** [verus-lang/verus#306]
Hello! I have a question about a potential QI (performance) issue in Verus.

Consider this snippet of Verus code:
```
spec fn abs(a: int) -> int
{
    if a >= 0 {
        a
    } else {
        -a
    }
}

#[verifier(nonlinear)]
proof fn equal_square_auto()
    ensures forall |a: int, b: int| a * a == b * b ==> abs(a) == abs(b)
{}

#[verifier(nonlinear)]
proof fn equal_square_auto2()
    ensures forall |a: int, b: int| a * a == b * b ==> abs(a) == abs(b)
{}

proof fn fact(a: int)
    requires a * a == 1
    ensures a == 1 || a == -1
{
    equal_square_auto();
    assert(abs(a) == abs(1));
}
```
where I have two auto lemmas `equal_square_auto` and `equal_square_auto2` with exactly the same statement.
And then in the `fact` proof function I’m using only the first lemma to prove something.

However, running `rust_verify` with `--profile-all` shows that both lemmas get instantiated:
```
note: Observed 20 total instantiations of user-level quantifiers

note: Cost * Instantiations: 448 (Instantiated 16 times - 80% of the total, cost 28) top 1 of 2 user-level quantifiers.
  --> test.rs:20:56
   |
20 |     ensures forall |a: int, b: int| a * a == b * b ==> abs(a) == abs(b)
   |             -------------------------------------------^^^^^^----^^^^^^
   |             |
   |             Triggers selected for this quantifier

note: Cost * Instantiations: 16 (Instantiated 4 times - 20% of the total, cost 4) top 2 of 2 user-level quantifiers.
  --> test.rs:25:56
   |
25 |     ensures forall |a: int, b: int| a * a == b * b ==> abs(a) == abs(b)
   |             -------------------------------------------^^^^^^----^^^^^^
   |             |
   |             Triggers selected for this quantifier
```
Furthermore, when I look at the terms used for instantiation of the first lemma `equal_square_auto`, it actually uses the skolem constants of the second lemma `equal_square_auto2` (which should be out of context).

Then I was trying to read the SMT query for this function, and the relevant parts look like this:
```
;; Function-Axioms crate::equal_square_auto
(declare-fun ens%equal_square_auto. () Bool)
(assert
 (= ens%equal_square_auto. (forall ((a~10$ Poly) (b~12$ Poly)) (!
    (=>
     ...
     (=>
      (= (Mul (%I a~10$) (%I a~10$)) (Mul (%I b~12$) (%I b~12$)))
      (= (abs.? a~10$) (abs.? b~12$))
    ))
    :pattern ((abs.? a~10$) (abs.? b~12$))
    :qid user_crate__equal_square_auto_0
    :skolemid skolem_user_crate__equal_square_auto_0
))))

;; Function-Axioms crate::equal_square_auto2
(declare-fun ens%equal_square_auto2. () Bool)
(assert
 (= ens%equal_square_auto2. (forall ((a~10$ Poly) (b~12$ Poly)) (!
    (=>
     ...
     (=>
      (= (Mul (%I a~10$) (%I a~10$)) (Mul (%I b~12$) (%I b~12$)))
      (= (abs.? a~10$) (abs.? b~12$))
    ))
    :pattern ((abs.? a~10$) (abs.? b~12$))
    :qid user_crate__equal_square_auto2_1
    :skolemid skolem_user_crate__equal_square_auto2_1
))))


; the actual VC
(assert
  (=>
   %%query%%
   (not (=>
     ens%equal_square_auto.
     ....
```

I think what’s happening here is that Z3 somehow matched the patterns `abs(...)` of the first lemma on the subterms of the skolemized version of the second (unused) lemma.

**Comment by parno** [comment]
Is it possible this is related to [this Z3 discussion/fix](https://github.com/Z3Prover/z3/discussions/6112)?  For example, if you rename the quantified variables in `equal_square_auto2`, does the issue persist?

**Comment by zhengyao-lin** [comment]
@parno Hmm it does seem like a similar issue. However, changing the variable names didn't help in my case: lemma 1 still instantiates on the subterms of lemma 2, and lemma 2 also gets instantiated on `a` and `1` (appearing in `fact`).

If I just change the formula of lemma 2 slightly, like to the following
```
#[verifier(nonlinear)]
proof fn equal_square_auto()
    ensures forall |a: int, b: int| a * a == b * b ==> abs(a) == abs(b)
{}

#[verifier(nonlinear)]
proof fn equal_square_auto2()
    ensures forall |c: int, d: int| c * c * c == d * d * d ==> abs(c) == abs(d)
{}
```
Then the second kind of instantiation (lemma 2 instantiating on terms in `fact`) does not happen anymore, but the first kind still happens.

**Comment by zhengyao-lin** [comment]
I was wondering if a potential solution is to just modify all definition of ensure clauses to use `define-fun`'s. For example:
```
(define-fun ens%equal_square_auto2. () Bool (forall ((a~10$ Poly) (b~12$ Poly)) (!
    (=>
     ...
     (=>
      (= (Mul (%I a~10$) (%I a~10$)) (Mul (%I b~12$) (%I b~12$)))
      (= (abs.? a~10$) (abs.? b~12$))
    ))
    :pattern ((abs.? a~10$) (abs.? b~12$))
    :qid user_crate__equal_square_auto2_1
    :skolemid skolem_user_crate__equal_square_auto2_1
)))
```
I was under the impression that z3 unfolds these macros very early, so maybe that would avoid the duplicated quantifiers to even appear in the goal.

**Comment by parno** [comment]
> I was wondering if a potential solution is to just modify all definitions of ensure clauses to use define-fun

Out of curiosity, does the problem go away if you apply that idea to `ens%equal_square_auto` and `ens%equal_square_auto2`?

**Comment by zhengyao-lin** [comment]
Yes it does work in my case. The only instantiations after the fix were lemma 1 applied on terms in `fact` (`a` and `1`).

**Comment by parno** [comment]
Interesting!  Thanks for trying the experiment.  @Chris-Hawblitzel Can you tell us more about the tradeoffs of using `declare-fun`+`assert` to define the ensures, vs. using `define-fun`?  We could also test it empirically to see what happens.

**Comment by Chris-Hawblitzel** [comment]
Thanks for raising this; this is a known issue for functions with 0 arguments.  The SMT encoding should either treat these specially or add a dummy argument.

**Comment by Chris-Hawblitzel** [comment]
Try it now.

**Comment by zhengyao-lin** [comment]
Thanks! I can confirm this fixed it in my case.
