### ISSUE TITLE
What is the best way to prove `new_strlit("a")@ + new_strlit("b")@ === new_strlit("ab")@`?

### ISSUE THREAD

**Issue by marshtompsxd** [verus-lang/verus#316]
Hi Verus team,

Thanks for adding the string support.
We need to frequently show that a string equals the concatenation of the other two strings like
```
new_strlit("a")@ + new_strlit("b")@ === new_strlit("ab")@
```
in our proof.

And it seems that every time we need to reveal every literal ("a", "b" and "ab") to prove equality.
This might not scale well and won't work if the literals come from outside.

I am wondering is there a better way to prove equality without revealing the literals?

**Comment by utaal** [comment]
If the `String`s / `StrSlice`s come from outside, they'll probably have a view (`@`) or other properties that carry information on what they contains, so you won't need (and won't be able to use) `reveal_strlit` for this.

If you're building strings from literals, you will need to use `reveal_strlit` to ask Verus to make their view visible in the encoding. Except if you're comparing two literals that are exactly equal, in which case you won't need `reveal_strlit` as we keep track of their identities, but I don't think this will come up much in proofs.

I'm going to close this, acknowledging that having to `reveal_strlit` may not scale (as we haven't seen it used much outside of tests yet), but feel free to reopen if you have further questions, or concrete scalability issues.
