### ISSUE TITLE
Error messages for pre/post-conditions with new syntax

### ISSUE THREAD

**Issue by utaal** [verus-lang/verus#338]
```
pub proof fn foo(&mut self) -> Option<nat>
  ensures true
{ ... }
```

results in: `error: ensures clause must be a closure`, which is an outdated message for the missing return value name (triaged by @tjhance).

It's possible that there are other similar error messages that need to be updated.

Reported by @TonyZhangND

**Comment by matthias-brun** [comment]
I noticed the same thing a while ago: #211

**Comment by utaal** [comment]
Oh! I thought it was something else. Closing as duplicate of https://github.com/verus-lang/verus/issues/211
