### ISSUE TITLE
Potential mistake in the tutorial. Unclear how to use `break` statements inside `while` loops.

### ISSUE THREAD

**Issue by lduranovic99** [verus-lang/verus#355]
I was reading the following [page](https://verus-lang.github.io/verus/guide/break.html) of the tutorial, and the last code snippet, which is
```rust
fn loop_triangle_break(n: u32) -> (sum: u32)
    ensures
        sum == triangle(n as nat) || (sum == 0xffff_ffff && triangle(n as nat) >= 0x1_0000_0000),
{
    let mut sum: u32 = 0;
    let mut idx: u32 = 0;
    while idx < n
        invariant
            idx <= n,
            sum == triangle(idx as nat),
        ensures
            sum == triangle(n as nat) || (sum == 0xffff_ffff && triangle(n as nat) >= 0x1_0000_0000),
    {
        idx = idx + 1;
        if sum as u64 + idx as u64 >= 0x1_0000_0000 {
            proof {
                triangle_is_monotonic(idx as nat, n as nat);
            }
            sum = 0xffff_ffff;
            break;
        }
        sum = sum + idx;
    }
    sum
}
```
discusses how using `break` statements in `while` loops is harder for the verifier, since the condition for the `while` loop may still be true even when there is an exit from the loop. The proposed solution in the tutorial is to introduce `ensures` clauses, which are supposed to specify what is true when the loop is exited, in any scenario. However, running this locally leads to the following.
```bash
error: expected curly braces
   --> loops-and-invariants.rs:108:11
    |
108 |           ensures
    |           ^^^^^^^
```
Could this be a problem with my local version of Verus, or is there perhaps a mistake in the tutorial?

**Comment by tjhance** [comment]
The full source for that guide snippet is at https://github.com/verus-lang/verus/blob/main/source/rust_verify/example/guide/recursion.rs and it should work on the latest Verus.

I'm not sure why you're getting that error, but if you post the full code you're trying to run, we might be able to help.

**Comment by lduranovic99** [comment]
Yeah that was it! I just forgot to update Verus in the past few weeks... Tried running it now with the full source and it worked like a charm! Thank you for the help.
