### ISSUE TITLE
Using `pervasive` standard library and macros across modules.

### ISSUE THREAD

**Issue by lduranovic99** [verus-lang/verus#356]
This "error" I'm seeing could definitely be due to my unfamiliarity with Rust's module system, and if that is the case, I apologize in advance... 

What I'm trying to do is write a little set library, and put all the code related to that in `set_library.rs`. Then that library needs to be imported in another file, call it `main.rs`. They both naturally need to use things from the `pervasive` "standard library", and I think I managed to do that. However, the macro `assert_by_contradiction!` just does not seem to be recognized in the file `set_library.rs`. Here is a minimal example:

### `set_library.rs`
```Rust
#[allow(unused_imports)]
use builtin::*;
#[allow(unused_imports)]
use builtin_macros::*;

#[allow(unused_imports)]
use crate::pervasive::*;
#[allow(unused_imports)]
use crate::pervasive::map::*;
#[allow(unused_imports)]
use crate::pervasive::option::*;
#[allow(unused_imports)]
use crate::pervasive::set::*;
#[allow(unused_imports)]
use crate::pervasive::set_lib::*;

verus! {

  pub proof fn lemma_nonempty_set_length_positive<A> (s: Set<A>)
    requires
      s.finite(),
      !equal(s, Set::empty()),
    ensures
      s.len() > 0,
  {
    assert_by_contradiction!(s.len() > 0, {
      assert(s.len() == 0);
      lemma_len0_is_empty::<A>(s);
    });
  }

  fn main ()
  {
  }

}
```

### `main.rs`
```Rust
#[allow(unused_imports)]
use builtin::*;
#[allow(unused_imports)]
use builtin_macros::*;

mod pervasive;
mod set_library;

#[allow(unused_imports)]
use pervasive::*;
#[allow(unused_imports)]
use pervasive::map::*;
#[allow(unused_imports)]
use pervasive::option::*;
#[allow(unused_imports)]
use pervasive::set::*;
#[allow(unused_imports)]
use pervasive::set_lib::*;

verus! {

  fn main ()
  {
  }

}
```

The output I'm getting is the following:
```bash
error: cannot find macro `assert_by_contradiction` in this scope
  --> set_library.rs:26:5
   |
26 |     assert_by_contradiction!(s.len() > 0, {
   |     ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: consider importing this macro:
           crate::assert_by_contradiction
   = help: have you added the `#[macro_use]` on the module/import?

error: aborting due to previous error

verification results:: verified: 0 errors: 0
```

My first question is whether I'm doing this inclusion of modules in a sensible way. In particular, is prepending `crate::` to the `use` statements involving the `pervasive` library something that I should be doing? Or is there a better way perhaps? My second question is about the problematic macro. My understanding is that I should not need anything else but
```Rust
use builtin_macros::*;
```
to use this macro in the `set_library` module. Is that correct? Thanks in advance!

**Comment by tjhance** [comment]
You can add `use crate::*;` to the `set_library.rs` file to get this to work.

The reason is that Rust always places macros at the top-level module, regardless of where they are defined. Therefore, the proper name for the `assert_by_contradiction` macro is `crate::assert_by_contradiction`.

It's actually possible for us to re-export macros from the macros they are defined in (and you'll notice that there are several other macros in our library where we do this). It's just that we haven't done this for `assert_by_contradiction` currently, so you need to refer to it via the root module.

**Comment by lduranovic99** [comment]
I see! Thanks so much for the help. This worked like a charm.
