### ISSUE TITLE
Is it possible to split a state machine into multiple files.

### ISSUE THREAD

**Issue by lduranovic99** [verus-lang/verus#365]
I'm looking to split my state machine (which I'm trying to verify) into a trusted file and potentially a couple of untrusted files. Is there a good way of doing this? Ideally, I would want to have the fields of the state machine, the invariants, and the transitions in one file, and then various proofs in another file or a set of files. Is there a good way of doing this now, or are we expected to have the whole state machine in one file? Thank you in advance!

**Comment by tjhance** [comment]
Unfortunately this isn't possible.

Originally I wanted to allow this, but it's a limitation of the proc-macro implementation. The invocation of the proc-macro needs to process the fields, transitions, invariants, and lemmas all at once.

**Comment by lduranovic99** [comment]
There's one ugly "fix" I was thinking about, and you can tell me if this makes any sense. Here's a minimal state machine file:
```rust
#[allow(unused_imports)]
use builtin::*;
#[allow(unused_imports)]
use builtin_macros::*;
mod helper;
use state_machines_macros::*;
#[allow(unused_imports)]
use helper::*;
verus! {
  state_machine! { 
    BRB {
      fields {
        pub sum: int,
        pub increment: int,
      }
      init!{
        initialize() 
        {
          init sum = 0;
          init increment = 0;
        }
      }
      transition!{
        initial(a: int, b: int) {
          require(a >= 0 && b >= 0);
          update sum = a;
          update increment = b;
        }
      }
      transition!{
        tick() {
          update sum = pre.sum + pre.increment;
        }
      }
      #[invariant]
      pub fn sum_positive(self) -> bool {
        self.sum >= 0
      }
      #[inductive(initialize)]
      fn initialize_inductive(post: Self) {
      }
      #[inductive(initial)]
      fn initial_inductive(pre: Self, post: Self, a: int, b: int) {
      }
      #[inductive(tick)]
      fn tick_inductive(pre: Self, post: Self) {
        // TODO: Figure out how to use code from `helper.rs` here...
        helper::tick_inductive(pre, post);
      }
    }
  }
  fn main() {
  }
}
```
This is the file that contains the state machine itself. It is also trying to import a function from the `helper.rs` file, which is something along the lines:
```rust
#[allow(unused_imports)]
use builtin::*;
#[allow(unused_imports)]
use builtin_macros::*;
#[allow(unused_imports)]
use crate::*;
#[allow(unused_imports)]
use crate::BRB::*;
#[allow(unused_imports)]
use state_machines_macros::*;
verus! {
  // TODO: Need to access the state machine here somehow...
  pub fn inductive_tick(pre: SM, post: SM) {
  }
  fn main() {
  }
}
```
Would it be possible to somehow access the data type of the state machine in this other file? I tried finding the data type in the source of the state machine macros, but with no luck... Sorry for the long post and thank you for the help!

**Comment by tjhance** [comment]
The struct with all the fields in it for your state machine would be `BRB::State`, so you should use that in place of where you wrote `SM`. `BRB::State` will also have a boolean predicate called `invariant` on it and as well as predicates that define the transitions.

There's also a bit of information [here](https://verus-lang.github.io/verus/state_machines/invariants.html#proving-the-inductive-criteria) about the `requires` and `ensures` you will need for the inductive theorems.

Also in general, the easiest way to see what the macro generates is by passing `-- -Zunpretty=expanded` to rust-verify.

**Comment by lduranovic99** [comment]
This was super helpful! Thanks for the help!
