### ISSUE TITLE
false type error on a bit-twiddling example

### ISSUE THREAD

**Issue by chanheec** [verus-lang/verus#369]
This example is from `rust_verify/example/bitvector_garbage.rs`

This error reports that `low` should not be a `Bool`. But this seems like a false positive since `get_bit!(result, low_loc)` is a boolean as well.

```
error: IntRange error: expected finite-width integer for bit-vector, got Bool
  --> rust_verify/example/bitvector_garbage.rs:63:38
   |
63 |         get_bit!(result, low_loc) == low,
   |                                      ^^^
```

It looks like we have been excluding this file from the CI since we updated the Z3 version.

Reported by @jaybosamiya

**Comment by tjhance** [comment]
fixed by 516efac4b5cdcc131f79c522b9ad9870d9e1e619
