### ISSUE TITLE
interpreter wrongly uses 32-bit truncation

### ISSUE THREAD

**Issue by tjhance** [verus-lang/verus#380]
```rust
proof fn test_shift() {
    assert((1usize << 40usize) == 0usize) by(compute);
}
```

This wrongly passes when `--arch-word-bits` is not set, because it truncates the shift to `arch_size_min_bits` which is set to 32. However, when `--arch-word-bits` is not set, the interpreter needs to account for the possibility that the arch size might be 64.

**Comment by jaybosamiya** [comment]
Huh, looks like my fix seems to break something I would not have expected to break. The fix should _basically_ work, but maybe I'm missing something obvious
