### ISSUE TITLE
open/closed should be required for trait spec fns

### ISSUE THREAD

**Issue by tjhance** [verus-lang/verus#382]
Right now we require every public spec fn to specify whether it's open or closed. Trait fns are all implicitly public, but we currently aren't doing this check for such functions.

**Comment by utaal** [comment]
backreference to related discussion (pointed out by @tjhance): https://github.com/verus-lang/verus/discussions/399

**Comment by utaal** [comment]
[Verus all-hands]
@tjhance has tried to fix this; but the syntax macro cannot tell if a trait is public or private.

We are going to need a new attribute for `closed` so we can do the detection in VIR.

The plan is to require it on bodies of the impl of public traits.
