### ISSUE TITLE
bitvector invalid AIR

### ISSUE THREAD

**Issue by tjhance** [verus-lang/verus#386]
Both of the following programs are invalid AIR:

```rust
proof fn test() {
    let b: u8 = 5;
    let w: u64 = 19; 

    assert(w >> (b as u64) == 0u64) by (bit_vector);
}
```

```rust
proof fn test() {
    let b: u8 = 5;
    let w: u64 = 19; 

    assert(b >= 3u64) by(bit_vector);
}
```

**Comment by tjhance** [comment]
the PR #420 fixes the first issue, but the second one remains

**Comment by utaal** [comment]
[Verus all-hands]

Planned resolution: allow the second pattern by widening.

**Comment by chanheec** [comment]
Currently, bit-vector operators do not like operands with different widths. 
`b >= 3u64` currently gives invalid AIR as `b` has a width 8, and `3u64` has a width 64.
As Andrea mentioned above, we could simply widen the smaller operand to the width of the bigger operand.
