### ISSUE TITLE
Incompleteness with some bitvector operations

### ISSUE THREAD

**Issue by jaybosamiya** [verus-lang/verus#415]
The following fails; changing the u64s to u32s still has it failing.

```rust
#[verifier(bit_vector)]
proof fn lemma_shift_right_u64_upper_bound(val: u64, amt: u64, upper_bound: u64)
  requires
    amt < 64u64,
    val <= upper_bound,
  ensures
    (val >> amt) <= (upper_bound >> amt)
{}
```

Changing to u16 has it succeed in 2~3 seconds, and changing to u8 has it succeed almost instantly, but that's not _too_ surprising.

Just as a quick point of comparison: a naive direct encoding into z3 is able to prove the above in ~75ms (~22ms for the 32-bit case)

**Comment by tjhance** [comment]
@jaybosamiya can you post your "naive direct encoding" for comparisons' sake?

**Comment by jaybosamiya** [comment]
```smt2
(declare-fun amt () (_ BitVec 64))
(declare-fun upper_bound () (_ BitVec 64))
(declare-fun val () (_ BitVec 64))
(assert (bvslt amt #x0000000000000040))
(assert (bvslt val upper_bound))
(assert (not (bvsle (bvashr val amt) (bvashr upper_bound amt))))
(check-sat)
```

Or as z3-py:
```py
from z3 import *
val, amt, upper_bound = BitVecs('val amt upper_bound', 64)
s = Solver()
s.add(amt < 64)
s.add(val < upper_bound)
s.add(Not ((val >> amt) <= (upper_bound >> amt)))
if s.check() == unsat:
    print("Much success, very proof, wow")
```

**Comment by chanheec** [comment]
I think the query Verus generates for this example is very similar to the above query, although it has several differences.
1) it currently carries all the context inherited from the parent module (including the prelude)
2) It uses incremental solving(i.e. push/pop)
3) negligible encoding differences with `query` and `location_label`
4) it uses tailored z3 options for bit-vector queries

---

With Z3 4.10.1, I got these results:
1) removing incremental solving made the query go through (i.e. removing the pair of push/pop around this query)
2) removing all the context(including prelude) made the query go through. However, removing the module's context(and retaining prelude) didn't make this query success.


I think we can consider applying 1) or/and 2) to bit-vector queries

---

This is the how the query looks like:
```smt2
 (declare-const val~2@0 (_ BitVec 64))
 (declare-const amt~4@0 (_ BitVec 64))
 (declare-const upper_bound~6@0 (_ BitVec 64))
 (assert
  (bvult amt~4@0 #x0000000000000040)
 )
 (assert
  (bvule val~2@0 upper_bound~6@0)
 )
 ;; postcondition not satisfied
 (declare-const %%location_label%%0 Bool)
 (declare-const %%query%% Bool)
 (assert
  (=>
   %%query%%
   (not (=>
     %%location_label%%0
     (bvule (bvlshr val~2@0 amt~4@0) (bvlshr upper_bound~6@0 amt~4@0))
 ))))
 (get-info :version)
 (assert
  %%query%%
 )
 (set-option :rlimit 30000000)
 (check-sat)
```



FWIW, this is the full smt file
[root__lemma_shift_right_u64_upper_bound_01.smt2.zip](https://github.com/verus-lang/verus/files/11069809/root__lemma_shift_right_u64_upper_bound_01.smt2.zip)

**Comment by parno** [comment]
At least in 2014, [Nikolaj attributed a result](https://stackoverflow.com/questions/26416814/why-does-z3-check-slow-when-it-is-immediately-preceded-by-z3-push) similar to Jay's to the use of `push` and `pop`, which seems to match @chanheec's findings as well.  That suggests we may want to skip issuing `push` and `pop` for BV queries.  At the very least, it might be worth trying that change with our existing tests/code to see how it affects the results.

**Comment by chanheec** [comment]
For the bitvector_garbage_collection example that fails with the current Z3 version, removing push/pop also made it go through instantly. I think I will go ahead and make changes to skip issuing push/pop for bit-vector queries

It seems like push/pop is issued in these locations
https://github.com/verus-lang/verus/blob/main/source/air/src/smt_verify.rs#L338
https://github.com/verus-lang/verus/blob/main/source/air/src/context.rs#L396
