### ISSUE TITLE
panic for 'continue' in while-loop

### ISSUE THREAD

**Issue by tjhance** [verus-lang/verus#421]
Verus panics on:

```rust
fn test() {
    let i = 7;
    while i < 5 {
        continue;
    }
}
```

```
thread 'rustc' panicked at 'assertion failed: !loop_info.some_cond', vir/src/sst_to_air.rs:1701:17
```
---

* [ ] un-ignore https://github.com/verus-lang/verus/commit/10e3049135b4c3cfefb397798e0d8412dd0d3862

**Comment by utaal** [comment]
[Verus all-hands]

Still fails on 6f6ccede

**Comment by utaal** [comment]
[Verus all-hands]

The tests we have for `continue` are for `loop`, not `while`.

**Comment by tchajed** [comment]
This does work (the `break` appears to be the important part):
```rust
use vstd::prelude::*;

verus! {
    fn foo() {
        let mut x = 0;
        while x < 100
        {
            x = x + 1;
            if (x < 10) {
                continue;
            } else {
                break;
            }
        }
    }

    fn main() {}
}
```

**Comment by tchajed** [comment]
This seems to be due to a loop with a continue being considered a "simple loop" when it's actually not-so-simple: https://github.com/verus-lang/verus/blob/6f6ccede9a4ab3a3d7819795b2837de37f679303/source/vir/src/ast_to_sst.rs#L1688-L1690.
