### ISSUE TITLE
Panic: generated ill-typed AIR code

### ISSUE THREAD

**Issue by jaybosamiya** [verus-lang/verus#444]
```rust
verus!{
    enum A { B }
    impl A {
        fn c(self) {
            let (d, e) = match self {
                A::B => (0, 0),
            };
        }
    }
}
```

leads to
```
thread 'rustc' panicked at 'internal error: generated ill-typed AIR code: error 'in equality, left expression has type Bool and right expression has different type tuple%2.' in expression '(= tmp%%1@ (tuple%2./tuple%2 (I 2) (I 3)))'', rust_verify/src/verifier.rs:386:21
```

It there are two or more variants in the enum, then it seems to work just fine; however, having exactly one enum variant is problematic.

---

Sidenote: the above test case was automatically minimized to the above (modulo capitalization and reindenting) from a much larger one using the minimizers introduced in #406

**Comment by tjhance** [comment]
fixed by 8565df57f3081e059ac52fee2d75a3f70a97871a
