### ISSUE TITLE
Crash in rustc when compiling ironsht library

### ISSUE THREAD

**Issue by jaylorch** [verus-lang/verus#454]
Compilation can produce an error in `rustc`. Here are repro instructions:

Check out commit `c2f189d4445a5f66cd0ceaa35835fad2b058e378` from `https://github.com/verus-lang/verus-systems-code/` and run `<path_to_verus>/source/tools/rust-verify.sh --crate-type=lib --compile ironfleet-comparison/ironsht/src/lib.rs`. You should get an error message like the following at the end:

```
verification results:: verified: 24 errors: 0
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /mnt/c/Apps/verus/rust/compiler/rustc_middle/src/hir/map/mod.rs:210:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by utaal** [comment]
This is a known unresolved issue when compiling with `--crate-type=lib` with ast-based erasure which we were unable to fix. Moving to `--erasure macro` (which will soon be the only supported mode) should fix it, but may cause some type check failures in code that was written without `--erasure macro`.

You can try: `<path_to_verus>/source/tools/rust-verify.sh --cfg erasure_macro_todo --erasure macro --crate-type=lib --compile ironfleet-comparison/ironsht/src/lib.rs`. I'm happy to help fix the breakage that this may cause.

**Comment by jaylorch** [comment]
Thanks, @utaal! It wasn't hard to fix the breakage, and now it compiles. :-)

**Comment by utaal** [comment]
Thank you!
