### ISSUE TITLE
main_new rust_verify.sh requires --release

### ISSUE THREAD

**Issue by tchajed** [verus-lang/verus#488]
Currently, if Verus is compiled in release mode, rust_verify.sh requires explicitly using it (and it will fail if Verus is not compiled in debug mode). I propose we change that so that the script tries release mode and falls back to debug if it isn't available, so that a flag is generally not required. We can then also have a `--debug` flag to force the debug profile (and/or  `--release` to force release profile), if there are use cases for those flags.

Thoughts on this? If folks agree on the plan I can go ahead and implement it.

**Comment by utaal** [comment]
That sounds good to me.

**Comment by tjhance** [comment]
Is there a way to have it determine which one is the most recent one built?

**Comment by utaal** [comment]
The mtime of `vstd.rlib` or `vstd.vir` could work.

**Comment by tchajed** [comment]
I think that would potentially be confusing and surprising if it's mtime based. For example if both are already up-to-date, re-building wouldn't change the mtimes. If you're iterating on verus and thus using debug builds, you can use `--debug` and definitely get the right one.

**Comment by tjhance** [comment]
yeah you're right the mtime wouldn't update ... oh well
