### ISSUE TITLE
Improve error message for exec-mode use of spec-mode builtin types

### ISSUE THREAD

**Issue by jonhnet** [verus-lang/verus#505]
This code:

```use builtin::*;
use builtin_macros::*;

verus!{

fn foo() -> nat {
    4 as nat
}

}
```

gives this error message:

```
error[E0605]: non-primitive cast: `i32` as `builtin::nat`
 --> ironsht/src/test.rs:7:5
  |
7 |     4 as nat
  |     ^^^^^^^^ an `as` expression can only be used to convert between primitive types or to coerce to a specific trait object
```

which confuses even people who should know better. It should instead tell us something like `nat isn't available in exec mode`, and perhaps `suggest adding spec modifier to fn`.

**Comment by utaal** [comment]
Moved to https://github.com/verus-lang/verus/discussions/387#discussioncomment-5584339
