### ISSUE TITLE
forall... implies... syntax: #[trigger] causes verification issues

### ISSUE THREAD

**Issue by tenzinhl** [verus-lang/verus#507]
Hey there, recently ran into an issue where when using the `forall... implies...` syntax there's this confusing bug where it seems like the generated code doesn't verify correctly when a `#[trigger]` annotation is included.

I tried making a minimal reproducing example but couldn't reproduce it at a smaller scale. Code that breaks is in the `verified-betrfs`, tagged as `tenzinhl-forall-implies-trigger-issue` (Link to repo at said commit: https://github.com/vmware-labs/verified-betrfs/tree/tenzinhl-forall-implies-trigger-issue)

The code in question looks like this:
```rust
pub proof fn map_plus_history_forall_lemma()
    ensures
      forall |stamped_map: StampedMap, history: MsgHistory|
      (
        stamped_map.value.wf()
        && history.wf()
        && history.can_follow(stamped_map.seq_end)
      ) ==>
      {
        &&& (#[trigger] Self::map_plus_history(stamped_map, history)).value.wf()
        &&& Self::map_plus_history(stamped_map, history).seq_end == stamped_map.seq_end + history.len()
      }
  {
    assert forall |stamped_map: StampedMap, history: MsgHistory|
      (
        stamped_map.value.wf()
        && history.wf()
        && history.can_follow(stamped_map.seq_end)
      ) implies
       // If the #[trigger] is removed here the module verifies
       (#[trigger] Self::map_plus_history(stamped_map, history).value.wf()
       && Self::map_plus_history(stamped_map, history).seq_end == stamped_map.seq_end + history.len())
    by
    {
      // When this assert is commented out, it complains that precondition to 295 isn't met, but
      // when left in it seems to trigger something and then it says 295 is fine.
      // assert(history.can_follow(stamped_map.seq_end));
      // This line is where it complains that precondition is not met!! 
      Self::map_plus_history_lemma(stamped_map, history);
      Self::map_plus_history_seq_end_lemma(stamped_map, history);
      assert(Self::map_plus_history(stamped_map, history).seq_end == stamped_map.seq_end + history.len());
    }
  }
```

Trying to verify this lemma yields this output:
```
error: precondition not satisfied
   --> coordination_layer/MsgHistory_v.rs:296:7
    |
263 |       history.can_follow(stamped_map.seq_end),
    |       --------------------------------------- failed precondition
...
296 |       Self::map_plus_history_lemma(stamped_map, history);
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Where line 296 is inside the body of the `forall... implies...` block. But this is confusing because `history.can_follow(stamped_map.seq_end)` is listed as one of the preconditions in the `forall... implies...` block.

The issue seems to be with how I'm using the `#[trigger]` annotation after the `implies` in the `forall... implies...` block. Removing the `#[trigger]` causes the module to verify fine.

**Comment by tenzinhl** [comment]
Changing:
```
      ) implies
       // If the #[trigger] is removed here the module verifies
       (#[trigger] Self::map_plus_history(stamped_map, history).value.wf()
       && Self::map_plus_history(stamped_map, history).seq_end == stamped_map.seq_end + history.len())
```
To
```
      ) implies
       // If the #[trigger] is removed here the module verifies
       ((#[trigger] Self::map_plus_history(stamped_map, history)).value.wf()
       && Self::map_plus_history(stamped_map, history).seq_end == stamped_map.seq_end + history.len())
```
(What I'm doing here is adding another pair of parens around the specific desired trigger) also has it verify without issue.

**Comment by utaal** [comment]
[Verus all-hands]

It seems likely this is due to some form of instability. The precondition succeeds on current `main`; we filed it as one of the instability cases to investigate: https://github.com/verus-lang/verus/discussions/147
