### ISSUE TITLE
thread 'rustc' panicked, generated ill-typed AIR code error message when asserting and running verus with `--expand-errors`

### ISSUE THREAD

**Issue by tenzinhl** [verus-lang/verus#561]
## Intro

Hey there, I wrote a `ext_equal` function on a custom data type. It's defined in terms of the `ext_equal`'s of its members. Eventually this calls the `ext_equal` of the builtin `set` and `map` types.

For some reason the assertion generated bad AIR code.

Error message:
```
thread 'rustc' panicked at 'internal error: generated ill-typed AIR code: error 'in call to vstd!set.Set.contains.?, argument #3 has type "bundle!spec.TotalKMMap_t.Key." when it should have type "Poly"' in expression '(vstd!set.Set.contains.? TYPE%bundle!spec.TotalKMMap_t.Key. (vstd!map.Map.dom.? TYPE%bundle!spec.TotalKMMap_t.Key.
```

## How to repeat

- Checkout the `verified-betrfs` repo at tag `tenzinhl-ext-equal-air-panic` (link to code at given commit: https://github.com/vmware-labs/verified-betrfs/tree/tenzinhl-ext-equal-air-panic)
- `cd` to `Splinter/src` in the repo
- Run `$verus --verify-module coordination_layer::CoordinationSystemRefinement_v bundle.rs --triggers-silent --expand-errors --multiple-errors 1` (replace `$verus` with your path to the `verus` executable)

## Notes
If you run without `--expand-errors` there's no output regarding this. Is this "ill-typed AIR code" error message expected when the `--expand-errors` flag is given?

The error message notes typing issues in the generated AIR code. Is this something that should be caught earlier by the type system?

**Comment by tjhance** [comment]
probably the same as issue #333

**Comment by tenzinhl** [comment]
It does look to be the same. Should this just be closed for now?

**Comment by utaal** [comment]
@tenzinhl can you please check if @Chris-Hawblitzel's fix https://github.com/verus-lang/verus/commit/4454b0cdc9b86f84021cc4a72fa6a1a0ed603443 for https://github.com/verus-lang/verus/issues/333 fixes this too?

**Comment by tenzinhl** [comment]
👍 I can try to get around to it this weekend.

**Comment by tenzinhl** [comment]
Yep there's no longer the AIR panic output anymore and `--expand-errors` provides helpful output with the "split assertion error" message showing what part of the conjunct failed.
