### ISSUE TITLE
On Windows, --profile always fails because z3tracer doesn't parse carriage returns

### ISSUE THREAD

**Issue by Chris-Hawblitzel** [verus-lang/verus#567]
I think this is actually an issue for https://github.com/verus-lang/smt2utils/tree/main/z3tracer , but I'll post it here because it causes an issue for Verus.  When using `verus --profile` on Windows, Z3 generates a log file that has carriage return characters in it.  When the Verus profiler sends this log file to `z3tracer`, the `z3tracer` lexer/parser fails because it only handles line feeds and spaces, not carriage returns.  Hopefully, it's easy to extend the `z3tracer` lexer/parser to handle carriage returns as another form of whitespace.

**Comment by parno** [comment]
I pushed an update that seems to solve the problem for some Z3 log files I manually converted to Windows line endings.  Please let me know if you're still seeing issues on a proper Windows machine.

**Comment by Chris-Hawblitzel** [comment]
Thanks!  That solved the lexing/parsing problem.
