### ISSUE TITLE
Command-line rlimit value gets lost

### ISSUE THREAD

**Issue by parno** [verus-lang/verus#569]
If I run:
```
verus --log-all --rlimit 1 example/trigger_loops.rs
```
Verus loops without terminating on `trigger_forever`, despite the command-line setting `rlimit` of 1.  Looking at the generated `root.smt2`, the very first `check-sat` (for `quantifier_example`) looks like this:
```
 (set-option :rlimit 3000000)
 (check-sat)
 (set-option :rlimit 0)
```
but all the rest of them look like:
```
 (set-option :rlimit 0)
 (check-sat)
 (set-option :rlimit 0)
```
meaning we're not actually imposing an rlimit.  

From some basic println tracing, it appears we only call this `Context::set_rlimit` once (with the value of `3000000`):
https://github.com/verus-lang/verus/blob/0f88d7974418dcd09698a5a78cbf97ca6bb5d526/source/air/src/context.rs#L187

Inside `smt_check_assertion`, we use that value before we issue a `check-sat`, but afterwards, we both issue a Z3 command to set rlimit to 0 *and* we update the context's rlimit to be 0, which it stays at for the rest of the file:
https://github.com/verus-lang/verus/blob/0f88d7974418dcd09698a5a78cbf97ca6bb5d526/source/air/src/smt_verify.rs#L230

I'm a bit puzzled as to how we ended up in this state, since it used to work.  I thought I'd check to see if anyone else knows before trying to fix it.

**Comment by Chris-Hawblitzel** [comment]
Oops ... that looks like it's my bug, just a few weeks ago in https://github.com/verus-lang/verus/pull/482/commits/666d8562b9ae981bb260735496ae39acc55f240b#diff-4fee287070902a029f2dea0aef25c3406038671f25769c24f9942ebf79aa90b5 .

I think it should be changed back to:

```
    pub(crate) fn set_z3_param_u32(&mut self, option: &str, value: u32, write_to_logs: bool) {
        if option == "rlimit" && write_to_logs {
            self.set_rlimit(value);
```

**Comment by Chris-Hawblitzel** [comment]
I reverted the code the introduced the bug.

**Comment by parno** [comment]
Cool, thanks for the quick diagnosis and fix!
