### ISSUE TITLE
Error defining a predicate on nat and Seq

### ISSUE THREAD

**Issue by zhengyao-lin** [verus-lang/verus#588]
Got an error when trying to define a predicate
```
use vstd::{prelude::*, seq::*};

verus! {

spec fn pred(a: nat, s: Seq<int>) -> bool
{
    a < s.len()
}

#[verifier(external)]
fn main() {}

} // verus!
```
Error:
```
error: The verifier does not yet support the following Rust feature: method call to method not defined in this crate
 --> test.rs:7:5
  |
7 |     a < s.len()
  |     ^
```

If I replace one of `a` and `s.len()` with a constant, then it works.

**Comment by Chris-Hawblitzel** [comment]
Here's a workaround for the moment: `#[allow(unused_imports)] use builtin::*;`

**Comment by utaal** [comment]
Triaged with @Chris-Hawblitzel.
I've landed a temporary hack as a workaround. We're working on a more permanent fix.

**Comment by utaal** [comment]
We overhauled the way we match items in https://github.com/verus-lang/verus/pull/605, which should address cases like this.
