### ISSUE TITLE
Nonlocal proof instability

### ISSUE THREAD

**Issue by jonhnet** [verus-lang/verus#593]
I've been seeing this kind of thing happen a bunch, but have had a difficult time pinning down a conspicuous enough example. Finally I have a smoking gun.

In this example, the hard part of the proof (the **then** branch of the if) passes when the **else** branch does `assume false`. When I begin working on the **else** branch, suddenly Verus forgets how to prove the **then** branch.

verus version: a673f9bedc069277a2989e9e504f6f9dd957f314 (June 8)

Run this and verus passes:
```
git clone git@github.com:vmware-labs/verified-betrfs.git
git checkout ce96f898ac4b01c68f06a52cb471827f378cdfe3
cd verified-betrfs/Splinter
$verus --time --expand-errors --multiple-errors 5 src/bundle.rs --verify-module journal::LinkedJournal_v --verify-function impl&%1::tight_sub_disk
```
Comment out line 606 of journal/LinkedJournal_v.rs and try again and watch the then branch start failing.

**Comment by jonhnet** [comment]
Going crazy here. Same method, grinding away on the else branch. Frustrated with line 622, I went to work on line 626 and suddenly the problem on line 622 is no problem. **so why did I waste my time debugging it!?**

```
git clone git@github.com:vmware-labs/verified-betrfs.git
git checkout 268f8c042634e73b059370673cc1f573c2f4cec0
cd verified-betrfs/Splinter
$verus --time --expand-errors --multiple-errors 5 src/bundle.rs --verify-module journal::LinkedJournal_v --verify-function impl&%1::tight_sub_disk
```

**Comment by jonhnet** [comment]
(also, line 626 is weird. I thought the point of `=~=` on line 618 was to obviate the need for a deeper `=~=` on 626?)

**Comment by jonhnet** [comment]
For clarity, the specific reason I'm "going crazy here" is that I'm now in a debugging cycle where success is indicated by no error (as it should be), and failure is indicated by a random assertion failure distant in the proof from where I'm working. Error messages have come unmoored from the case I'm working on, so now the only feedback from Verus I can extract is a single bit.

**Comment by jonhnet** [comment]
Oh noooes. Whether this function verifies or not depends on whether I do function-scoped verification with --verify-function. yikes

**Comment by tjhance** [comment]
does #[verifier::spinoff_z3] help?

**Comment by jonhnet** [comment]
Am i holding it wrong? I put that attr above my proof fn and:
```
error: unrecognized verifier attribute
   --> src/journal/LinkedJournal_v.rs:498:5
    |
498 |     #[verifier::spinoff_z3]
```

**Comment by tjhance** [comment]
sorry it's actually #[verifier(spinoff_prover)]

**Comment by utaal** [comment]
Moving to the tracking discussion https://github.com/verus-lang/verus/discussions/147#discussioncomment-6170768
