### ISSUE TITLE
Panic when using const generic

### ISSUE THREAD

**Issue by ziqiaozhou** [verus-lang/verus#617]
https://github.com/verus-lang/verus/blob/main/source/rust_verify/src/lifetime_generate.rs#L570

fn mk_typ_args<'tcx>(
    ctxt: &Context<'tcx>,
    state: &mut State,
    node_substs: &[rustc_middle::ty::subst::GenericArg<'tcx>],
) -> Vec<Typ> {
    let mut typ_args: Vec<Typ> = Vec::new();
    for typ_arg in node_substs {
        match typ_arg.unpack() {
            GenericArgKind::Type(ty) => {
                typ_args.push(erase_ty(ctxt, state, &ty));
            }
            GenericArgKind::Lifetime(_) => {}
            _ => panic!("typ_arg"),
        }
    }
    typ_args
}

**Comment by tjhance** [comment]
It looks like mk_typ_args now has a case for GenericArgKind::Const, so I'm going to mark this as fixed.
