### ISSUE TITLE
Broken external for a module

### ISSUE THREAD

**Issue by ziqiaozhou** [verus-lang/verus#618]
The earlier version of verus can apply verifier(external) to an entire module using the following commit.
https://github.com/verus-lang/verus/commit/8c80c19ccd46d87cd3aa756cba7b9c5da3995d2e

However, the latest verus does not support verifier(external) to an entire module anymore.

**Comment by tjhance** [comment]
Fixed in 3bdce905e61213b4004fd082386790a5d2cf220d, test added in 27278d1d86ee4186b56d67854af714ad62a859f2
