### ISSUE TITLE
proof instability / flakiness

### ISSUE THREAD

**Issue by jonhnet** [verus-lang/verus#681]
I'm running into lots of cases where touching something somewhere in a file causes a failure in an unrelated `fn`. Informally, it seems like this happens a _lot_ in verus, where it was very rare in Dafny. 

Here's a particularly egregious case. Add this completely standalone function `commute_transitivity` to the file, and a proof a hundred lines prior suddenly stops verifying.

Such flakiness is very disheartening; it changes the user experience from "a long slog" to "am I even making forward progress?"

Repro:
```
git clone git@github.com:vmware-labs/verified-betrfs.git
git checkout c4e28489b98851127ae017bfc7c51a97bfc298ef
cd verified-betrfs/Splinter
$verus --time --expand-errors --multiple-errors 5 src/bundle.rs --verify-module journal::LinkedJournal_v::LinkedJournal --verify-module journal::LinkedJournal_v --verify-module journal::LinkedJournalRefinement_v
```
...passes, but uncomment `commute_transitivity` and unrelated `build_tight_is_awesome` fails.

**Comment by yizhou7** [comment]
which version of verus are you using @jonhnet ?

**Comment by jonhnet** [comment]
ce715d977f801747d12b35079b4ed073f48b9e43 from yesterday

**Comment by jonhnet** [comment]
Just hit another spooky-flake-at-a-distance:
```
git clone git@github.com:vmware-labs/verified-betrfs.git
git checkout f1135cd2f93f5bef694f590284e422d612ecc27d
cd verified-betrfs/Splinter
$verus --time --expand-errors --multiple-errors 5 src/bundle.rs --verify-module journal::LinkedJournal_v::LinkedJournal --verify-module journal::LinkedJournal_v
```

**Comment by jonhnet** [comment]
@yizhou7 note that I made a copy-paste mistake in my repro instructions in the first comment above; it wasn't `--verify-module`ing the module with the actual change in it. Corrected above.

**Comment by yizhou7** [comment]
I ran mariposa on the repo state **before the change** that would trigger instability, for the above two cases respectively. FWIW, the two failing functions were labeled as unstable at that point already. 

The comment on the query:
`;; Function-Def bundle::journal::LinkedJournal_v::DiskView::build_tight_is_awesome`

```
query: gen/journal__LinkedJournalRefinement_v.smt2_/split.10.smt2
| mutation   | status   | success      | mean(second)   | std(second)   |
|------------|----------|--------------|----------------|---------------|
| overall    | unstable | x            | x              | x             |
| shuffle    | unstable | 36/61 59.0%  | 0.05           | 0.01          |
| rename     | stable   | 61/61 100.0% | 0.05           | 0.01          |
| reseed     | stable   | 61/61 100.0% | 0.05           | 0.0           |
| quake      | unstable | 51/61 83.6%  | 0.03           | 0.0           | 
```

The comment on the query:
`;; Function-Def bundle::journal::LinkedJournal_v::DiskView::tight_empty_disk`
```
query: gen/journal__LinkedJournal_v.smt2_/split.17.smt2
| mutation   | status   | success      | mean(second)   | std(second)   |
|------------|----------|--------------|----------------|---------------|
| overall    | unstable | x            | x              | x             |
| shuffle    | stable   | 61/61 100.0% | 0.02           | 0.0           |
| rename     | stable   | 61/61 100.0% | 0.02           | 0.0           |
| reseed     | stable   | 61/61 100.0% | 0.02           | 0.0           |
| quake      | unstable | 37/61 60.7%  | 0.01           | 0.0           |
```

**Comment by utaal** [comment]
Moved to https://github.com/verus-lang/verus/discussions/147.
