### ISSUE TITLE
Misdirected span in 'recommendation not met' error message

### ISSUE THREAD

**Issue by jonhnet** [verus-lang/verus#691]
The span at line 32 isn't a recommends clause, so I don't know what to do with this message. Recording attached.

[2023-07-18-13-40-24.zip](https://github.com/verus-lang/verus/files/12088858/2023-07-18-13-40-24.zip)

```
warning: recommendation not met
  --> src/journal/PagedJournalRefinement_v.rs:32:15
   |
32 |             { Self::i_opt(*self.prior_rec, boundary_lsn).concat(self.message_seq) }
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
37 |         ojr.is_Some() ==> ojr.unwrap().valid(boundary_lsn),
   |         -------------------------------------------------- recommendation not met
```

**Comment by jonhnet** [comment]
I am dumb and read the error message backwards.

**Comment by jonhnet** [comment]
There's actually a UI issue hiding in here. The order of (offending line, recommendation violated) depends on where they appear in the file. That makes reading these messages confusing, because the subject/object order flips around.

**Comment by tjhance** [comment]
I agree, that's confusing. I'm not sure what to do about it though, since we're relying on Rust's output mechanism ...

**Comment by utaal** [comment]
As this is an error message issue, closing in favor of https://github.com/verus-lang/verus/discussions/387#discussioncomment-6540541
