### ISSUE TITLE
--record feature is freakin' awesome.

### ISSUE THREAD

**Issue by jonhnet** [verus-lang/verus#703]
I sure love lowering the bar to communicating new issues unambiguously. That is all.

Feel free to close this bug as "working as intended".

**Comment by utaal** [comment]
Let me second @jonhnet's comment. It's already been really useful and it promises to be very helpful in the future.

Thank you @ahuoguo, @elaustell, and @jaybosamiya.

@elaustell, you are the assignee, feel free to close as "working as intended" once you see this :) Thanks!
