### ISSUE TITLE
Cannot reveal a function with an `impl` in it

### ISSUE THREAD

**Issue by jaybosamiya** [verus-lang/verus#704]
```rust
use vstd::prelude::*;

fn main() {}

verus! {

  trait X {}
  impl X for int {}

  #[verifier::opaque]
  spec fn foo(x: impl X) -> bool {
    true
  }

  proof fn test()
  {
    // reveal(foo);
    // Suggests: reveal::<_>(foo);

    // reveal::<_>(foo);
    // Says: cannot infer type of the type parameter `F` declared on the function `reveal`

    // reveal(foo::<_>);
    // Says: this function takes 0 generic arguments but 1 generic argument was supplied

    assert(foo(3int));
  }

}
```

There is no way for us to pass the `assert` above, since there is no way to reveal `foo` it. Various invocations of `reveal` with their messages from Verus are documented above.

---

Tested on:

```console
Verus
  Version: 0.2023.07.20.2dc6a17
  Profile: release
  Platform: macos_aarch64
  Toolchain: 1.68.0-aarch64-apple-darwin
```

---

Me, to `foo`:

![All right then, keep your secrets](https://github.com/verus-lang/verus/assets/5683582/a5e5b216-f29e-429a-9153-4974cfc2a92d)

**Comment by jaybosamiya** [comment]
Note: this is not a very high priority since there is a simple workaround---don't use `impl` and actually give the parameter's type an actual name. For example,
```rust
  #[verifier::opaque]
  spec fn foo<T: X>(x: T) -> bool {
    true
  }
```

**Comment by tjhance** [comment]
This problem was discussed recently. The plan is to support `reveal(foo);` without type arguments. See https://github.com/verus-lang/verus/issues/119

**Comment by utaal** [comment]
Thank you for the report; as this is the same underlying issue as https://github.com/verus-lang/verus/issues/119, I'm closing this one.
