### ISSUE TITLE
impl Drop should be disallowed

### ISSUE THREAD

**Issue by tjhance** [verus-lang/verus#723]
Verus doesn't complain if you do,

```rust
impl Drop for X {
    fn drop(&mut self)
        requires false,
    {
    }
}
```

you could do unsound things inside the 'drop' implementation

**Comment by Chris-Hawblitzel** [comment]
For now, can we (a) disallow the requires clause on `drop` or (b) require `drop` to be `#[verifier::external]`?

**Comment by tjhance** [comment]
another (really annoying) consideration is 'opens_invariants'. For exec functions, this defaults to 'opens_invariants any'. But drop could in principle be called while an invariant is open.
