### ISSUE TITLE
Panic or strange error message when using `Seq<Tracked<S>>`

### ISSUE THREAD

**Issue by jaylorch** [verus-lang/verus#758]
The following code causes a verifier panic: `thread 'rustc' panicked at 'internal error: ill-typed AIR code: name vstd!seq.Seq<main!S.>. is already in scope', rust_verify\src\verifier.rs:334:17`:
```
    pub struct S
    {
    }

    pub proof fn bug(ps: Seq<&Tracked<S>>)
        ensures
            ps.map(|_i: int, p: &Tracked<S>| p@).len() >= 0
    {
    }
```

The following similar code yields the strange message `error: variable shadowing not yet supported`:
```
    pub struct S { }

    pub proof fn bug(ps: Seq<&Tracked<S>>)
        ensures
            ps.map(|_i: int, p: &Tracked<S>| p).len() >= 0
    {
    }
```

Even if the reference to the tracked object is never referred to in the closure, we still get the strange message `error: variable shadowing not yet supported`:
```
    pub struct S
    {
    }

    pub proof fn bug(ps: Seq<&Tracked<S>>)
        ensures
            ps.map(|i: int, _p| i).len() >= 0
    {
    }
```

**Comment by tjhance** [comment]
Probably related to #705 

For collections of tracked objects, vstd best supports the use of `Map<K, V>` where `V` is some tracked type. Also, it's generally recommended to keep the `Tracked< ... >` on the outside, where it can be easily peeled off.
