### ISSUE TITLE
Recommends for a `pub closed spec fn` should be allowed to refer to private items in the module

### ISSUE THREAD

**Issue by utaal** [verus-lang/verus#782]
* [ ] @utaal fill in.

Found by @GenericMonkey.

**Comment by tjhance** [comment]
What's the rationale for this? It seems surprising to me. The function could be called from outside the module so the recommends clause could be emitted there.

**Comment by utaal-b** [comment]
You're right. I don't remember what the rationale was, but this cannot make sense as-is.
