### ISSUE TITLE
adding assertion breaks proof

### ISSUE THREAD

**Issue by jonhnet** [verus-lang/verus#806]
I have a proof that passes with `assert(a<=b); assert(b<=c)`. If I add -- not replace, but add -- the statement `assert(a<=b,=c)`, the proof fails. That's ... weird. See AllocationJournal_v.rs:585 in the attached report.
[2023-09-08-12-04-31.zip](https://github.com/verus-lang/verus/files/12562960/2023-09-08-12-04-31.zip)

**Comment by utaal** [comment]
Moved to https://github.com/verus-lang/verus/discussions/147#discussioncomment-7347893
