### ISSUE TITLE
reveal_with_fuel doesn't work inside state_machine! macro

### ISSUE THREAD

**Issue by jonhnet** [verus-lang/verus#823]
```
[2023-09-20-13-28-11.zip](https://github.com/verus-lang/verus/files/12677314/2023-09-20-13-28-11.zip)
error: unexpected token
   --> src/allocation_layer/AllocationJournal_v.rs:468:101
    |
468 | ...n_Journal::State::build_lsn_au_index_au_walk, 10 );
    |                                                ^
```

**Comment by jonhnet** [comment]
[2023-09-20-13-53-48.zip](https://github.com/verus-lang/verus/files/12677460/2023-09-20-13-53-48.zip)

(reuploading a recording)

**Comment by tjhance** [comment]
I fixed the comma token problem. However, it doesn't entirely resolve the issue; we now get the strange:

```
error: `use` import is not supported in `trait`s or `impl`s
```

Which I'm guessing is related to #839

**Comment by utaal** [comment]
I think https://github.com/verus-lang/verus/pull/840 should fix this too. (You're just getting further in compilation and now this other error -- which @jonhnet et al have been dealing with for a while -- shows up.)

**Comment by utaal** [comment]
This should be fixed, please reopen if it reappears.
