### ISSUE TITLE
Verus panics when implementing a trait with an equality bound on `View`

### ISSUE THREAD

**Issue by pratapsingh1729** [verus-lang/verus#833]
The following code ([playground link](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=fc9dc4d1703feea9fbdd9816da8a0bf4)):
```
pub trait ViewOption {
    type X;
}

impl<T:View> ViewOption for Option<T>
{
    type X = Option<T::V>;
}
```
causes the following panic in Verus:
```
thread 'rustc' panicked at 'assertion failed: state.trait_decl_set.contains(&trait_path_vir)', rust_verify/src/lifetime_generate.rs:409:21
```
Notably, this seems to be something to do with `View`, as the following works ([playground link](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=c84c6fb595635ffb35f44f1e32f2e606)):
```
pub trait Blah {
    type V;
}

pub trait ViewOption {
    type X;
}

impl<T:Blah> ViewOption for Option<T>
{
    type X = Option<T::V>;
}
```

**Comment by Tracyee** [comment]
FYI, #724 could be a similar issue (which hasn't been fixed🥲)
