### ISSUE TITLE
Verus panics when implementing a trait for Seq

### ISSUE THREAD

**Issue by Tracyee** [verus-lang/verus#836]
This happens when I try to implement a `DeepView` trait for my project. This might not be needed eventually but just as a bug report:)

[Link to Verus Playground](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=3d5e7f8129955ebf85d215f789906537)
```rust
use vstd::prelude::*;

verus! {

pub trait DeepView {
    type V;
    spec fn deep_view(&self)->Self::V;
}

impl<T: DeepView> DeepView for Seq<T> {
    type V = Seq<T::V>;
    open spec fn deep_view(&self) -> Self::V
    {
        self.map_values(|e : T| e.deep_view())
    }
}

fn main();
}
```

Got:
```
$ verus foo.rs
thread 'rustc' panicked at 'Box', vir/src/sst_to_air.rs:968:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If remove the spec body, Verus does not panic:
```rust
use vstd::prelude::*;

verus! {

pub trait DeepView {
    type V;
    spec fn deep_view(&self)->Self::V;
}

impl<T: DeepView> DeepView for Seq<T> {
    type V = Seq<T::V>;
    open spec fn deep_view(&self) -> Self::V;
}

fn main();
}
```

Got:
```
$ verus foo.rs
verification results:: 1 verified, 0 errors
```

## Backtrace

<details>
  <summary>Expand</summary>
<pre>
$ RUST_BACKTRACE=1 verus foo.rs
thread 'rustc' panicked at 'Box', vir/src/sst_to_air.rs:968:41
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: vir::sst_to_air::exp_to_expr
   4: vir::sst_to_air::exp_to_expr
   5: vir::sst_to_air::exp_to_expr
   6: vir::sst_to_air::exp_to_expr
   7: vir::func_to_air::func_body_to_air
   8: rust_verify::commands::OpGenerator<D>::handle_specs_scc_component
   9: rust_verify::commands::OpGenerator<D>::next
  10: rust_verify::verifier::Verifier::verify_bucket
  11: rust_verify::verifier::Verifier::verify_crate_inner
  12: rust_verify::verifier::Verifier::verify_crate
  13: std::thread::local::LocalKey<T>::with
  14: <rust_verify::verifier::VerifierCallbacksEraseMacro as rustc_driver_impl::Callbacks>::after_expansion
  15: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
  16: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</pre>

</details>

---

Tested on
```
Verus
  Version: 0.2023.09.27.f0e4909
  Profile: release
  Platform: macos_aarch64
  Toolchain: 1.70.0-aarch64-apple-darwin
```

**Comment by tjhance** [comment]
Looks like this was fixed at some point.
