### ISSUE TITLE
Choose a greatest value in a map

### ISSUE THREAD

**Issue by euclidgame** [verus-lang/verus#844]
I have a map `m` (`Map<A, nat>`) whose domain is finite and I want to choose the greatest value in it. What I have tried was:

```rust
let domain = m.dom();
let r = |a1: A, a2: A| m[a1] <= m[a2];
let max_a = domain.find_unique_maximal(r);
domain.find_unique_maximal_ensures(r);
domain.lemma_maximal_equivalent_greatest(r, max_a);
let max_value = m[max_a];
```

However, the values in `m` are not unique, so `r` is not a total ordering and I can't use those lemmas. Then I tried to find the greatest value in set `m.values()` by
```rust
let r = |n1: nat, n2: nat| n1 <= n2;
let values = m.values();
let max_value = values.find_unique_maximal(r);
values.find_unique_maximal_ensures(r);
values.lemma_maximal_equivalent_greatest(r, max_a);
```
But I don't know how to prove `values` is finite which seems obvious. I wonder if there's some ways to prove it or find a greatest value without using `find_unique_maximal`.

**Comment by parno** [comment]
If you know that `dom()` is finite, then you can use `lemma_values_finite` to show the `values` are finite as well:

https://github.com/verus-lang/verus/blob/8e7df0f2fd33ea90519585ae684752660f0b962e/source/pervasive/map_lib.rs#L306

**Comment by tjhance** [comment]
Also note you'll need to update verus. (I added the lemma just now.)

**Comment by euclidgame** [comment]
Thanks, it works!
