### ISSUE TITLE
Assertion fails when second conjunct is the one containing the trigger

### ISSUE THREAD

**Issue by jaylorch** [verus-lang/verus#845]
The following code fails the assertion, suggesting a trigger issue.
```
pub struct P
{
    pub x: int
}

pub proof fn test7(m: Map<int, P>, s: Seq<int>)
    requires
        forall |i| 0 <= i < s.len() ==> m.dom().contains(i) && m[i].x == #[trigger] s[i],
{
    if s.len() > 0 {
        let i: int = 0;
        assert(0 <= i < s.len());
        assert(m.dom().contains(i) && m[i].x == s[i]); // this assertion fails
    }
}
```

It seems to be because the first conjunct doesn't contain the trigger, even though the entire term does. It seems this way because the following works:
```
pub proof fn test7(m: Map<int, P>, s: Seq<int>)
    requires
        forall |i| 0 <= i < s.len() ==> m.dom().contains(i) && m[i].x == #[trigger] s[i],
{
    if s.len() > 0 {
        let i: int = 0;
        assert(0 <= i < s.len());
        assert(m[i].x == s[i]);
        assert(m.dom().contains(i));
    }
}
```

**Comment by parno** [comment]
This doesn't help much, but FWIW, I recall occasionally hitting cases like this and receiving the explanation that if Z3 tries to prove `A && B`, it's quite possible that it tries to prove `A`, fails, and then gives up without ever considering `B`, even for triggering purposes.  In other words, I don't think Z3 is guaranteed to examine the entire expression searching for triggers before it tries to start solving.

**Comment by jaylorch** [comment]
Ah, I see. It's a known bug in Z3. Thanks.

**Comment by tjhance** [comment]
It's a known issue, but it also sucks. It's mildly annoying if you're aware of it and know to look out for it; it's hugely frustrating if you don't know what's going on.
