### ISSUE TITLE
Misparse/mislex of `macro_rules!` macro in presence of `=~=`

### ISSUE THREAD

**Issue by jaybosamiya** [verus-lang/verus#866]
Generally it is possible to auto-generate code via a `macro_rules!` invocation that uses Verus syntax, as long as you make sure to generate a `verus! { ... }` wrapper around the generated code too. This unfortunately breaks for `=~=` (extensional equality) for reasons as of yet unknown.

Minimized example:
```rs
macro_rules! temp {
  () => {
    verus! {
      proof fn foo() {
        assert(seq![1,2] =~= seq![1,2]);
      }
    }
  };
}
temp!{}
```
which complains about `error: expected expression` at the `~`. Note that we don't find any such issue with most of our other introduced syntax (such as `@` or `&&&`).

[playground link](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=a9c4cb32db04fb90637a4301dc0c32e2)

**Comment by utaal** [comment]
I think this may be due/related to the fact that the `verus!` macro has to recombine the tokens that make up `=~=` and nested invocations may interfere with that. For the time being, as a workaround, you should be able to use `::builtin::ext_equal` for `=~=` and `::builtin::ext_equal_deep` for `=~~=`.
