### ISSUE TITLE
Add a Warning/Error when using `=~~=` on type without `#[verifier::ext_equal]` annotation

### ISSUE THREAD

**Issue by tenzinhl** [verus-lang/verus#873]
Currently when using the `=~~=` syntax on a user defined type, there is no warning when the `#[verifier::ext_equal]` annotation is not added to said type. Instead assertions will just always fail (even though to my understanding this is always a clear misuse to use `=~~=` operator without having the `#[verifier::ext_equal]` annotation on the compared types).

Would it be possible to add a compiler warning or error for this case? (I'd be interested in looking into this with some guidance).

**Comment by utaal** [comment]
Moved to https://github.com/verus-lang/verus/discussions/387#discussioncomment-7433018. I'd be happy to help you look into this, ping me on Zulip/Slack.
