### ISSUE TITLE
Panic due to internal error about missing variant

### ISSUE THREAD

**Issue by jaylorch** [verus-lang/verus#881]
In the attached example, I get the following mysterious error. It seems to be related to returning a tracked tuple with a postcondition.

```
thread '<unnamed>' panicked at 'internal error: missing variant DistributedSystemController', vir\src\ast_util.rs:475:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'rustc' panicked at 'worker thread panicked', rust_verify\src\verifier.rs:1717:39
thread '<unnamed>' panicked at 'could not send!: SendError { .. }', rust_verify\src\verifier.rs:154thread ':<unnamed>64' panicked at 'could not send!: SendError { .. }', rust_verify\src\verifier.rs:154:64
```

[2023-11-02-14-46-14.zip](https://github.com/verus-lang/verus/files/13244913/2023-11-02-14-46-14.zip)

**Comment by utaal** [comment]
The error message is a bug.

The underlying issue is that `DistributedSystemController` has a mix of private and public fields, which we don't yet support.

**Comment by jaylorch** [comment]
Thanks for the quick explanation! It's really easy for me to fix that issue by just making all the fields `pub`.

**Comment by jaylorch** [comment]
But I'll leave this open since, as you say, the panic is a bug.
