### ISSUE TITLE
Can't use `assert` in `open_atomic_invariant!` in proof mode

### ISSUE THREAD

**Issue by upamanyus** [verus-lang/verus#883]
The problem: using `assert()` inside of `open_atomic_invariant!` within a `proof fn` causes Verus to complain `error: already in proof mode`.

Example:
```
use vstd::{prelude::*, invariant::*};

verus!{
    struct TrivialPredicate { }
    impl InvariantPredicate<int, u32> for TrivialPredicate {
        closed spec fn inv(k: int, v: u32) -> bool { true }
    }

    fn ok(tracked i: AtomicInvariant<int, u32, TrivialPredicate>)
        opens_invariants any
    {
        open_atomic_invariant!(&i => inner => {
            assert(2 == 2);
        });
    }

    proof fn bad(tracked i: AtomicInvariant<int, u32, TrivialPredicate>)
        opens_invariants any
    {
        open_atomic_invariant!(&i => inner => {
            // BUG: error: already in proof mode
            assert(2 == 2);
        });
    }

    pub fn main() {}
}
```

**Comment by Chris-Hawblitzel** [comment]
We could remove the "already in proof mode" restriction and allow proof blocks inside proof mode.  But it sounds like there would still be an underlying problem: syntax.rs translates some things differently in ghost mode than in exec mode, so we don't want it running with the wrong mode.

Having two different `open_atomic_invariant!` macros sounds like the easiest workaround.  A more difficult alternative would be to integrate `open_atomic_invariant` directly into syntax.rs, as part of the Verus syntax and part of the procedural macro for the Verus syntax.

Another idea, which I'm not sure would work, would be to have `inv_macro_exprs` process `$eexpr` but leave `$bblock` as a raw token tree to be processed later, when the ghostness is known.

**Comment by upamanyus** [comment]
For the last idea: I thought the reason that `inv_macro_exprs` is processing `$bblock` at all is that macros are expanded from outside to inside. So, the first thing that happens is the outermost `verus!` macro rewrites a bunch of stuff (where it knows exactly the ghostness of every block since it walks from the top down) and leaves the `open_atomic_inv!` as-is. Afterwards, `verus_inv_macro_exprs!` will get expanded, but if we leave `$bblock` as a raw token tree there, there's no further macro that'll be able to process it.

With "eager" macros, might a more principled approach be to *first* expand the `open_atomic_invariant!` macro, then expand the `verus!` macro last? With this, `open_atomic_invariant!` would sit above the "verus code" abstraction. I.e. it would only need to emit code that a human might have written inside of `verus!`, where e.g. `assert` statements get dealt with correctly. Right now, it's instead trying to emit some post-processed code, instead of "verus code".

**Comment by tjhance** [comment]
trouble is there's no way to expand macros from inside out. (there are some unstable proc-macro features that kind of let you do this, but they aren't nearly ready for what we'd want to do.)

**Comment by Chris-Hawblitzel** [comment]
I agree, I don't see how to make the delayed processing of `$bblock` work.  Yet another idea, which I'm not sure would work: if syntax.rs is aware of `open_atomic_invariant!`, can it automatically redirect this to a different macro invocation in proof mode?  If this works, it would probably be easy to implement.

**Comment by upamanyus** [comment]
I was able to get automatic rewriting of the macro invocation (#886) by doing a rewrite in `syntax.rs`. I'm not sure if this is actually desirable though, if e.g. a user decides to shadow the `open_atomic_invariant!` macro with their own thing, this would rewrite that. It also doesn't currently work if the macro is called via e.g. `invariant::open_atomic_invariant!` (the rewrite looks for an exact string match), so I'm inclined to get rid of it unless there's a simple way to better match the things we want to rewrite.
