### ISSUE TITLE
verus loses track of a fact about non-mutable variables

### ISSUE THREAD

**Issue by jonhnet** [verus-lang/verus#953]
[2024-01-02-17-17-55.zip](https://github.com/verus-lang/verus/files/13814996/2024-01-02-17-17-55.zip)

At the requires (and a couple test assertions), `slice.valid(data@)` is true. But by line 380, the fact is no longer provable. Both slice and data are immutable.

**Comment by tjhance** [comment]
The variable `slice` is shadowed.

```
        let oelt = 
            match self.try_get(slice, data, idx) {
                None => None,
                Some(slice) => {    // new variable `slice` is defined here
```

**Comment by jonhnet** [comment]
Oh that's simply embarrassing. Can we quietly remove this from the Internet so it doesn't follow me around for the rest of my days? :)

Also languages should disallow shadowing.

Thanks for the spot.
