### ISSUE TITLE
spec functions need tr_bound predicates

### ISSUE THREAD

**Issue by tjhance** [verus-lang/verus#974]
broadcast_forall functions are guarded by 'tr_bound' predicates. Spec functions, currently, are not, but spec functions can be used to effectively broadcast information. We need to add 'tr_bound' predicates to spec functions too. (It might be OK to restrict this to recursive functions.)

Example:

```rust
pub trait Tr {
    spec fn bool_function(b: bool) -> bool;

    proof fn bool_function_true_is_false()
        ensures Self::bool_function(true) == false;
}

#[verifier::decreases_by]
proof fn dby<T: Tr>(b: bool) {
    T::bool_function_true_is_false();
}

pub open spec fn spec_fn_with_implications<T: Tr>(b: bool) -> bool
    decreases (if b { 1nat } else { 0 })
        via dby::<T>
{
    if b == false {
        false
    } else {
        !spec_fn_with_implications::<T>(T::bool_function(b))
    }
}

struct X { }

impl Tr for X {
    open spec fn bool_function(b: bool) -> bool { true }

    proof fn bool_function_true_is_false()
    {
    }
}
```

Observe that the spec function of `spec_fn_with_implications` effectively broadcasts the fact that `T::bool_function(true) == false`. To make use of this fact, you need some triggers. I'm not sure if it's possible to observe it right now, it might be possible with the experiments to use other trigger strategies?

As an example, see the attached AIR file:

[ttrait.air.txt](https://github.com/verus-lang/verus/files/14170660/ttrait.air.txt)

This is modified from the original AIR with the addition of the following:

```
  (assert
   ("assertion failed" "assertion failed")
   (ttrait!spec_fn_with_implications.? $ TYPE%ttrait!X. (B true))
  )
  (assume
   (ttrait!spec_fn_with_implications.? $ TYPE%ttrait!X. (B true))
  )
```

**Comment by tjhance** [comment]
- [ ] add tr_bound to spec functions
- [ ] add tr_bound to the closure_req and closure_ens axioms that were recently added as part of the FnDef PR
- [ ] see if it's possible to use MBQI to make a self-contained test case

**Comment by Chris-Hawblitzel** [comment]
Definitely a soundness issue.  Z3 has the right to instantiate quantifiers even when there aren't any obvious terms that would trigger them.

The proposed fix sounds like the right fix.

I think it should be ok to omit preconditions from non-recursive function definition axioms, since these are equivalent to abbreviations that could be inlined everywhere without the need for any axioms.
