### ISSUE TITLE
expected expression, found `%`

### ISSUE THREAD

**Issue by jonhnet** [verus-lang/verus#982]
Here's a surprising error that popped up in the `trait-default-resolve` branch:
```rust
error: expected expression, found `%`
   --> src/marshalling/SeqMarshalling_v.rs:446:40
    |
446 |             let oelt = self.try_get_elt(slice, data, idx as usize);
    |                                        ^
```

There are no `%` characters in that entire file. :v) This is not a blocking issue for me; it's not occurring on my current repo.  (Note to self: my branch is `jonh/marshalled-accessors-messy-types`.)

[2024-02-13-08-27-36.zip](https://github.com/verus-lang/verus/files/14269431/2024-02-13-08-27-36.zip)

**Comment by Chris-Hawblitzel** [comment]
Fixed by https://github.com/verus-lang/verus/pull/981/commits/9aca6ff5f9627cceb6056557914815c5c75093f5
