### ISSUE TITLE
Soundness issue in sequence axioms (axiom_seq_add_index2)

### ISSUE THREAD

**Issue by tchajed** [verus-lang/verus#990]
The axiom `axiom_seq_add_index2` is unsound:

https://github.com/verus-lang/verus/blob/214c3d8c005fec86914b3cc92447f27312b0c2c3/source/pervasive/seq.rs#L352-L357

Here's a proof of false:

```rs
use vstd::prelude::*;

verus! {
    proof fn seq_bad()
        ensures false
    {
        let s1: Seq<int> = seq![1];
        let s1_2: Seq<int> = seq![1, 2];
        let s2: Seq<int> = seq![];
        assert(s1.add(s2)[0] == s2[-1]);
        assert(s1_2.add(s2)[1] == s2[-1]);
    }

    fn main() {}
}
```

The lemma becomes true if the precondition is changed to `0 <= s1.len() <= i`.

**Comment by Chris-Hawblitzel** [comment]
Oops.  That's a good motivation for https://github.com/verus-lang/verus/pull/988 .

**Comment by Chris-Hawblitzel** [comment]
Fixed by https://github.com/verus-lang/verus/commit/bf057b6c2991c4106d4176975564b9e51ce5a468
